githru/githru-vscode-ext

- packages/view/src/components/TemporalFilter/TemporalFilter.tsx
- packages/view/src/components/TemporalFilter/index.ts
- packages/view/src/types/global.d.ts
- view 부분 4가지 기능 중 하나인 temporal filter 부분을 위한 컴포넌트 구조를 만들었습니다.
- 임시 type 추가를 위한 global any type을 추가했습니다.
> feat: add `TemporalFilter` component

- .github/workflows/analysis-engine.yml
- packages/analysis-engine/src/NodeTypes.temp.ts
- analysis-engine 파이프라인 에러 수정
- circular type definition으로 발생하는 에러 수정
- Job 명칭 변경
> fix: treat lint error from circular type definition

- packages/view/fake-assets/convert.js
- packages/view/fake-assets/sampleClusterNodeList.json
@jejecrunch 님이 요청해주셨던, message field 빠진 부분 채워서 다시 넣었습니다 : -)
> chore(view): add (missing) message field in samples.

- .all-contributorsrc
- CONTRIBUTING.md
> fix: all-contributors bot config 수정

- package-lock.json
- package.json
- packages/analysis-engine/package.json
- packages/view/package.json
- packages/vscode/package.json
- version을 모두 0.1 타겟으로 변경하였습니다.
(@ansrlm 님, 토욜에 install 에러가 났던게 `0.1.0` 을 `0.1`로 써서 였던 것으로 ... ㅜ.ㅜ)
- vscode에 engine dependency를 걸었습니다.
이제 vscode에서 import * from engine 이렇게 쓸 수 있어요
TODO
- engine에서 type.d.ts 이런것? export 하기.
> build: GOGO! version 0.1.0

- packages/vscode/.eslintrc.json
- packages/vscode/.prettierrc.json
- packages/vscode/.vscode/extensions.json
- packages/vscode/.vscode/settings.json
- packages/vscode/package.json
- packages/vscode/src/commands.ts
- packages/vscode/src/extension.ts
- packages/vscode/src/webview-loader.ts
- packages/vscode/tsconfig.json
- packages/vscode/webpack.config.js
status bar에 githru Launch button을 붙였습니다.
일단 여기를 출발점으로 삼을께요. 나머지 고고고!
> feat(vscode): add status bar button, chore(vscode): prettify

- package-lock.json
- packages/view/package.json
- packages/view/src/components/TemporalFilter/TemporalFilter.util.ts
날짜별 commit, cloc를 가져오고 오름차순으로 정렬하였습니다.
> feat: temporalfilter util 함수 추가

- packages/view/src/App.tsx
- packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.tsx
- packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.util.ts
- packages/view/src/components/Statistics/Statistics.tsx
- packages/view/src/components/TemporalFilter/TemporalFilter.tsx
- packages/view/src/components/VerticalClusterList/VerticalClusterList.tsx
- packages/view/src/types/global.ts
정말 급하게 작성했습니다,,,
바로 수정해서 작업해주시면 감사드리겠습니다..
> enhance(view): add FilteredData & SelectedData

- packages/view/src/components/TemporalFilter/ClocLineChart/ClocLineChart.tsx
- packages/view/src/components/TemporalFilter/CommitLineChart/CommitLineChart.tsx
- packages/view/src/components/TemporalFilter/TemporalFilter.util.ts
commit chart를 뷰에 나타나도록 기능구현만 하였습니다.
@jeonghye-choi 님이 지적해주신 잘못된 로직이나, 리팩토링, 컨벤션등은 민정님과 정혜님과 같이 수정할 계획입니다.
> feat(view): commit chart 추가

- packages/vscode/package.json
vscode package.json의 command를 register된 command에 맞게 수정했습니다.
> fix(vscode): fix wrong command

- CONTRIBUTING.md
extension 실행에 관한 부분을 추가했습니다.
F5 눌러서 extension을 실행했을 때, 아래와 같은 워닝이 뜨는데요.
debug anyway 하면 되지만 거슬려서요.
해당 문제가 아래 이미지처럼 tasks.json의 $ts.wepack.watch와 $tslint.webpack.watch problem matcher가 없기 때문인 것 같은데
아래 extension을 설치하는 것 뺴고는 마땅한 해결 방법이 보이지 않네요. 혹시 다른 해결방법은 없을까요 @__@?
https://marketplace.visualstudio.com/items?itemName=amodio.tsl-problem-matcher
> docs: contributing.md 수정

- package-lock.json
- packages/view/src/components/TemporalFilter/ClocLineChart/ClocLineChart.scss
- packages/view/src/components/TemporalFilter/ClocLineChart/ClocLineChart.tsx
- packages/view/src/components/TemporalFilter/CommitLineChart/CommitLineChart.tsx
- packages/view/src/components/TemporalFilter/TemporalFilter.scss
- packages/view/src/components/TemporalFilter/TemporalFilter.tsx
`9bf0bac`
y축 지우고 차트명 추가했습니다.
`29d3e4e`
모드 지원하는 체크박스 얘기가 더 없어서 우선은 주석처리했습니다.
`9366f9b`
날짜 컨트롤 윗 부분이 비던데 의도하신 부분인지 잘 모르겠지만 채운 편이 좀 더 좋은 것 같아서 채웠습니다 !
의도하셨다면 죄송합니다 (_ _)
|AS-IS|TO-BE|
|---|---|
|<img width="400" alt="스크린샷 2022-09-12 오후 9 29 13" src="https://user-images.githubusercontent.com/41473964/189598479-ab190dbf-942e-4931-a3cb-08a6dd6de7ec.gif">|<img width="400" alt="스크린샷 2022-09-12 오후 9 29 13" src="https://user-images.githubusercontent.com/41473964/189655027-77103978-0f05-4504-baf7-558f846f4dd6.gif">|
> fix(view): fix some issues of temporal filter #145

- packages/view/CONTRIBUTING.md
View Feature에 대한 CONTRIBUTING.md를 작성하기 위해 Template을 작성했습니다.
내용을 모두 채우진 못해 여러분들의 도움이 필요할거라 생각하여 Template만 작성하여 PR 날립니다.
빠른 작성을 위해 approve 2개가 달성되면 바로 merge 하겠습니다.
> add View CONTRIBUTING.md Template

- packages/analysis-engine/CONTRIBUTING.md
- packages/analysis-engine/README.md
- readme.md
- contributing.md
- 추후 추가 예정
> feat(engine): add contributing and readme files

- packages/analysis-engine/CONTRIBUTING.md
- packages/analysis-engine/README.md
> feat(engine): add contributing.md

- packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.scss
- 기존 background color와 동일하게 option background color 지정
> style(view): fix option background color

- packages/view/src/App.tsx
- packages/view/src/components/TemporalFilter/ClocLineChart/ClocLineChart.tsx
- packages/view/src/components/TemporalFilter/CommitLineChart/CommitLineChart.tsx
- packages/view/src/components/TemporalFilter/TemporalFilter.tsx
상위 Filter와 아래 차트들이 연동되게 하였습니다.
이것은 v0.1.0의 임시 조치이고, brushing 연동때는 재정비될 예정입니다.
> fix(view): sync Filter to charts.

- package-lock.json
- packages/view/README.md
`373871c`
README.md 파일을 생성하고 기본적인 내용은 엔진팀 README.md를 참고했습니다.
기능에는 우선 제가 이해한 부분을 요약해서 적어놓은 터라 틀린 부분도 있을 것 같다는 생각도 듭니다.
우선 merge 후 각자 변경할 사항이 있다면 변경해보는 게 좋을 것 같습니다.
> docs(view): add README.md in view

- packages/view/src/components/TemporalFilter/TemporalFilter.tsx
filteredData 자체를 reverse 해서 넘겼습니다.
> fix(view): fix clusternode list ordering

- packages/view/src/components/TemporalFilter/Filter/Filter.tsx
datepicker 초기값이 안 나오던 부분 fix 하였습니다.
(일단 러프하게 짰는데, 추후에 리팩토링 한 번 해야겠습니다)
> fix(view): fix initial datepicker value

- packages/analysis-engine/CONTRIBUTING.md
> chore(engine): update contributing.md

- package-lock.json
- packages/view/package.json
- packages/view/src/components/VerticalClusterList/Summary/Summary.scss
- packages/view/src/components/VerticalClusterList/Summary/Summary.tsx
회의에서 이야기한대로, 우선은 깊이 서치하지 않고 도입했습니다. npm trend를 보니, mui icons랑 react icons가 많이 쓰이는 것 같은데, mui icons는 뭔가 딸려와야하는 게 많은 것 같아서 react-icons로 선택했습니다.
- AS-IS
- TO-BE
- #201
> feat(view): apply react-icons library and fix error about nested element

- packages/view/src/components/VerticalClusterList/Summary/Summary.util.ts
#216 PR이 합쳐짐에 따라 Summary.util.ts도 수정했습니다.
approved 받으면 관련 이슈인 #174 도 닫겠습니다 😄
> fix(view): fix typo in newline escape seq in view

- package-lock.json
- packages/analysis-engine/src/csm.spec.ts
- packages/analysis-engine/src/csm.ts
- packages/analysis-engine/src/index.ts
- packages/analysis-engine/src/parser.ts
- packages/analysis-engine/src/stem.spec.ts
- packages/analysis-engine/src/stem.ts
- packages/view/package.json
- packages/view/src/App.scss
- packages/view/src/components/VerticalClusterList/VerticalClusterList.scss
- packages/view/src/ide/ExecuteIDECommands.ts
- packages/view/src/ide/ExecuteIDECommandsImpl.ts
- packages/view/src/ide/VSCodeAPIWrapper.ts
- packages/vscode/package.json
Ready for using vscodeApi in webview.
> feat(view): add vscodeapiwrapper and openDocument command

- package-lock.json
- packages/analysis-engine/.eslintrc.json
- packages/analysis-engine/package.json
- packages/analysis-engine/rollup.config.js
- packages/analysis-engine/src/index.ts
- packages/analysis-engine/src/pluginOctokit.ts
- packages/analysis-engine/tsconfig.json
- PR 상세 데이터 및 PR 관련 commits 데이터 크롤링
- @anpaul0615 님~ 사용할 데이터 관련해서 필요한 부분 말씀해주시면 그부분만 제공할 수 있도록 인터페이스를 작업 하겠습니다.
- discord / comments / DM 등으로 말씀 부탁드립니다.
- WIP (이부분은 제외하고 보시면 좋을 것 같습니다)
- vscode에서 owner / repo정보 전달 필요
- lifecycle적용 (최악의 경우 tsyringe 삭제 예정)
> feat(engine): collect data related to pull request

- package-lock.json
- packages/analysis-engine/src/index.ts
- packages/analysis-engine/src/pluginOctokit.ts
- packages/vscode/src/extension.ts
- packages/vscode/src/utils/git.util.ts
- pull_request의 전체 목록을 가져옵니다.
- workspace path에 의거해서 git owner / repo를 추출하고, 해당 값을 통해서 pull_request들을 가져옵니다.
> feat(vscode): dynamic initialization with token, owner, and repo

- packages/view/src/components/VerticalClusterList/Summary/Author/Author.tsx
- packages/view/src/components/VerticalClusterList/Summary/Summary.scss
기존의 avatar에서 avatar 이미지가 있어도 author의 첫글자가 떴습니다.
이를 보완해서 image가 있으면 첫글자가 뜨지 않도록 수정하였습니다.
|AS-IS|TO-BE|
|---|---|
| <img src="https://user-images.githubusercontent.com/41473964/193344297-ff177a36-df9f-4ead-8f1e-f6f9da9bf6da.png" width="300" /> | <img src="https://user-images.githubusercontent.com/41473964/193465675-5cb97939-e502-4f94-b9c9-56ac42628533.png" width="300" /> |
> feat(view): show background color if no image

- packages/view/src/components/Detail/Detail.tsx
- packages/view/src/components/Detail/Detail.type.ts
- packages/view/src/components/Statistics/Statistics.hook.tsx
- packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.hook.tsx
- packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.tsx
- packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.type.ts
- packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.util.ts
- packages/view/src/components/VerticalClusterList/Summary/Content/Content.tsx
- packages/view/src/components/VerticalClusterList/Summary/Summary.tsx
- packages/view/src/components/VerticalClusterList/Summary/Summary.type.ts
- packages/view/src/components/VerticalClusterList/Summary/Summary.util.ts
- packages/view/src/components/VerticalClusterList/VerticalClusterList.util.ts
- packages/view/src/hooks/useGlobalData.tsx
- packages/view/src/types/global.ts
- closed #208
- selectedCluster를 다중으로 선택하는 작업을 하였습니다.
빠르게 작업하다보니 에러부분만 수정을 하였습니다.
동작에는 이상이 없다고 생각하지만, 아무래도 array로 작업하다보니 2중 배열로 동작하게되어 성능 이슈가 있을 것이라 판단됩니다.
파일 용량 문제로 gif로 올립니다.
> feat(view): add the feature of selecting multiple clusters

- packages/view/src/components/Detail/Detail.hook.tsx
- packages/view/src/components/Detail/Detail.util.ts
- packages/view/src/components/VerticalClusterList/Summary/Summary.util.ts
- #252 
- close #263
- cluster PR제목을 커밋 첫번째 메세지에서 제목으로 수정하였습니다
- merge 커밋이 맨 아래로 올 수 있도록 순서를 변경하였습니다
<br />
이런식으로 `Merge pull request #159 from vgihan/main` 머지 커밋은 이대로 하는게 좋을까요??
<br />
> fix(view): cluster 제목 수정

- packages/view/src/components/TemporalFilter/LineChart.const.ts
- packages/view/src/components/TemporalFilter/LineChart.scss
- packages/view/src/components/TemporalFilter/LineChart.ts
- packages/view/src/components/TemporalFilter/TemporalFilter.scss
- packages/view/src/components/TemporalFilter/TemporalFilter.tsx
- packages/vscode/src/webview-loader.ts
기존의 CLOC, Commit LineChart 두 가지 component를 LineChart Component하나로 refactoring 하였습니다.
> refactor(view): extract method from line charts

- packages/view/.prettierrc.yaml
- packages/view/src/components/TemporalFilter/LineChart.const.ts
- packages/view/src/components/TemporalFilter/LineChart.ts
- packages/view/src/components/TemporalFilter/LineChartBrush.ts
- packages/view/src/components/TemporalFilter/TemporalFilter.tsx
refer #250
- Added Brush Base (not interactive yet)
- Fixed CLOC chart data
- Refactored LineChart Component
- Adjusted Axis (+interactive ticks)
- Add interactive brushing
> feat(view): add brush to temporal filter

- packages/view/.prettierrc.yaml
- packages/view/src/components/TemporalFilter/LineChart.ts
- packages/view/src/components/TemporalFilter/LineChartBrush.ts
- packages/view/src/components/TemporalFilter/TemporalFilter.tsx
- packages/view/src/components/TemporalFilter/TemporalFilter.util.ts
refer #250
added filtering by brushing in temporal filter
- remove date filter
- add reset button
> feat(view): added filtering by brushing in temporal filter

- package-lock.json
- packages/view/package.json
- packages/vscode/.vscode/settings.json
fix #312 
also, set default npm.packageManager as `npm` in our workspace.
(you will not see `yarn` issue on the watcher anymore).
> fix(all): upgrade node-sass version for #312

- package-lock.json
#333 
- 버전이 여러개 설치된 패키지를 하나로 합쳐서 에러를 해결하였습니다.
> bug(view): de-duplicate multiple versions (#333)

- packages/vscode/src/webview-loader.ts
#316 
view-panel icon 변경하기
변경 전
변경 후
더 효율적인 방법이 논의해보면 좋을 것 같습니다
> feat(vscode): change view-panel icon(#316)

- packages/view/src/ide/VSCodeIDEAdapter.ts
- packages/view/src/react-app-env.d.ts
- packages/view/src/types/EngineCommand.ts
- packages/vscode/src/extension.ts
- packages/vscode/src/webview-loader.ts
[vscode] 기준 Branch 선택 #278
1. vscode Package에서 "getBranchList" 커맨드를 통해 view에서 branch의 목록을 가져올 수 있도록 하였습니다.(#278)
2. vscode, view 통신에서 부정확한 command가 전달될 경우 콘솔에서 확인가능하도록 하였습니다.
새로운 command 추가, 부정확한 경우 콘솔 출력
> feat(vscode): Add Branch Select Feature (#278)

- packages/view/src/components/Detail/Detail.tsx
- packages/view/src/components/VerticalClusterList/Summary/Content/Content.tsx
- packages/vscode/src/extension.ts
resolve #324
[view] PR 머지 커밋일 경우, PR로 바로 이동하는 링크 추가 #324
> feat(view) PR 머지 커밋일 경우, PR로 바로 이동하는 링크 추가 (#324)

- packages/view/src/components/BranchSelector/BranchSelector.scss
- packages/view/src/components/BranchSelector/BranchSelector.tsx
> fix(view): Fix Class Name #348

- packages/view/src/App.scss
- packages/view/src/App.tsx
- packages/view/src/components/BranchSelector/BranchSelector.scss
- packages/view/src/components/Detail/Detail.scss
- packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.scss
- packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.const.ts
- packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.tsx
- packages/view/src/components/TemporalFilter/LineChart.scss
- packages/view/src/components/TemporalFilter/TemporalFilter.scss
- packages/view/src/components/ThemeSelector/ThemeSelector.scss
- packages/view/src/components/ThemeSelector/ThemeSelector.tsx
- packages/view/src/components/ThemeSelector/index.ts
- packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.scss
- packages/view/src/components/VerticalClusterList/Summary/Summary.scss
- packages/view/src/components/index.ts
- packages/view/src/constants/constants.tsx
resolve #330 
- 사용자가 색상을 선택하면, 그래프 부분의 색을 일관 변경되도록 하였습니다.
> feat(vscode, view): change theme color (#330)

- package-lock.json
- packages/view/.gitignore
- packages/view/package.json
- packages/view/playwright.config.ts
- packages/view/tests/home.spec.ts
#364
- playwright dependency 추가
- playwright config 세팅
- firefox 주석
- base url 생성
- 테스트 시 web server 실행
- home(title, branch) test
- e2e test 뿐 아니라 유닛 테스트(jest) 등을 포함한 테스트들에 대한 전략 또는 컨벤션이 한번 잡으면 좋을 것 같습니다.
- e2e test의 경우 인터페이스, ui, 유저 시나리오에 대한 내용 테스트가 핵심이라고 판단되어 명확히 정의된 무언가....(문서 싫지만 ...) 가 없으면 추후 변동에 대해 부담이 될 가능성이 높다라는 생각도 듭니다!
> feat(view): Setting playwright(e2e test)

- package-lock.json
- packages/view/src/services/index.ts
> fix(view): fix dependency error

- packages/view/src/components/TemporalFilter/TemporalFilter.tsx
- packages/view/src/components/ThemeSelector/ThemeSelector.tsx
- packages/view/webpack.prod.config.js
https://github.com/githru/githru-vscode-ext/pull/383#discussion_r1292788367
services 디렉토리에 alias를 추가하여 absolute path 를 사용하도록 개선했습니다.
> refactor(view): services 디렉토리 alias 추가

- packages/view/src/components/TemporalFilter/TemporalFilter.scss
closed #427
- position 변경을 통한 hover 우선순위 변경
- 간격을 맞춰주기 위해 top에서 margin-top 변경
> fix(view): 새로고침 버튼 overlap시 hover 상실

- packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.util.test.ts
- packages/view/src/components/VerticalClusterList/VerticalClusterList.util.test.ts
- packages/view/tests/fakeAsset.ts
resolve #419 
ClusterGraph.utill test코드 작성 했습니다. 
(모두 계산식이라 계산이 잘되는지만 확인했습니다.)
VerticalClusterList test를 merge할 때 수정을 잘못해서 오류도 고쳤습니다..
> feat(view): ClusterGraph.utill test코드 작성 및 VerticalClusterList test 오류 수정

- packages/analysis-engine/src/index.ts
- packages/view/src/components/VerticalClusterList/VerticalClusterList.util.test.ts
- packages/vscode/src/extension.ts
- packages/vscode/src/setting-repository.ts
- packages/vscode/src/webview-loader.ts
fix(vscode, engine): error handing while crawling pull requests
> fix(vscode, engine): error handing while crawling pull requests

- packages/analysis-engine/src/index.ts
- packages/view/src/components/Detail/Detail.hook.tsx
- packages/view/src/components/VerticalClusterList/VerticalClusterList.util.test.ts
- packages/vscode/src/extension.ts
- packages/vscode/src/setting-repository.ts
- packages/vscode/src/utils/git.util.ts
- packages/vscode/src/webview-loader.ts
> fix(view): re-order detail commit list (by desc)

- packages/vscode/package.json
- packages/vscode/src/commands.ts
- packages/vscode/src/extension.ts
> feat(vscode): add feature for resetting github auth by deleting saved auth.

- package.json
- packages/analysis-engine/package.json
- packages/view/package.json
- packages/vscode/README.md
- packages/vscode/package.json
> feat(all): v0.6.0 release

- packages/vscode/src/extension.ts
- packages/vscode/src/webview-loader.ts
fixes #315 
webview panel 이 계속 생성되는 문제를 해결했습니다.
> fix(vscode): Prevent multiple webview panel instances

- packages/vscode/src/extension.ts
> fix(vscode): fix preventing multiple panel issues (webview is disposed)

- .github/CODEOWNERS
- .github/workflows/e2eTests.yml
2024년을 위한 CODEOWNERS파일을 업데이트 하였습니다.
리뷰 및 승인 부탁드립니다.
* 임시로 view의 e2e test를 disable합니다. 이 부분은 따로 이슈로 올리겠습니다.
> env: update codeowners for 2024

- CONTRIBUTING.md
> fix: CONTRIBUTING.md 오타 수정

- README.md
#547 
23명의 contributors로 하드코딩 된 배지를 
#547 영택님의 피드백을 반영하여 
contributors 배지를 제거합니다.
> docs: 하드코딩 된 contributors 배지 제거 #547

- .github/workflows/ci.yml
- package-lock.json
- packages/view/package.json
#596 에서 논의하고 #607 에서 확정한 ui 프레임워크 mui를 설치하였습니다.
package.json을 업데이트하였습니다.
원랜 svg 5개를 mui icon으로 교체하여 함께 pr하려고 했으나 (매우 간단하기 때문에..) #608 에서 고민이 생겨 보류하고 설치만 먼저 PR 올립니다!
> mui, mui icon 설치

- README.md
#189 
- [wiki](https://github.com/githru/githru-vscode-ext/wiki)에 과거 작성된 문서를 추가하고 README에도 wiki 링크를 추가합니다.
- 위키와 이슈가 거의 정리되어 있어서 작성된 이슈 링크를 위키에 모으는 작업만 했습니다. 레포 내에 위키로 연결된 링크가 없는 것 같아서 README에 추가했습니다!
> [all] knowledge 수합 및 마이그레이션

- packages/view/src/components/TemporalFilter/LineChartBrush.ts
- packages/view/src/components/TemporalFilter/TemporalFilter.tsx
#551 
https://github.com/user-attachments/assets/72bdb1c0-7dde-444a-8643-59dbb0e2b46e
- LineChart 컴포넌트에서 Create, Drawr, Reset으로 관심사를 분리했습니다.
- LineChart Brushing 이후 Reset 버튼을 추가하여 UX를 개선하였습니다.
Reset 버튼 UI의 디자인에 관련된 의견 부탁드립니다😄
> fix(view) : 상단 라인 차트 전체 기간에서 특정 기간으로 Brushing 후 Reset 기능 버튼 추가 

- packages/vscode/src/extension.ts
- packages/vscode/src/webview-loader.ts
#488
#577
#577 이전의 상태로 아래 파일들을 롤백 합니다.
webview-loader.ts
extension.ts
vscode 모듈 내의 webview-loader.ts, extension.ts 두 파일의 fetcher 함수 관련 dependencies관련 내용들을 롤백합니다.
엔진 성능 최적화 팀과 함께 협의 후 관련 코드를 변경하고자 합니다.
> Revert(vscode): vscode 모듈 #577 이전으로 롤백

- packages/vscode/README.md
doc(vscode): update release notes
> doc(vscode): update release notes

- .github/workflows/analysis-engine.yml
#657
설정 텍스트 수정 `16.x` &rarr; `20.x`
analysis-engine.yml 파일의 node-version 수정
> [engine] analysis-engine.yml github action node 버전업 (20.x LTS)

- package-lock.json
- package.json
- packages/analysis-engine/package.json
- packages/view/package.json
- packages/vscode/package.json
> env(all): ready for release 0.7.1

- packages/view/src/components/BranchSelector/BranchSelector.scss
- packages/view/src/components/BranchSelector/BranchSelector.tsx
close #695 
- 원래부터 로컬에서 개발할 때 branchList가 아무것도 없는 게 맞는지 모르겠습니당.. 첨부드린 사진은 임시로 코드 내에서 테스트를 위해 임의로 브랜치 배열을 만들어서 style을 적용시킨 예시라고 생각해주시면 될 것 같습니다!
- author bar chart select box 부분을 mui로 바꾸기 위해 이슈 생성해 둔 상태(#696) 입니다! 현재 style과 일치하게 작업할 것 같습니다.
> [view] 상단 branch select style 수정

- package-lock.json
원활한 작업을 위해 main 브랜치와의 버전을 동기화 했습니다.
> fix: package-lock.json 최신화

- packages/view/src/utils/debounce.test.ts
- packages/view/src/utils/throttle.test.ts
- debounce 테스트 결과
- throttle 테스트 결과
- `utils` 폴더 내부의 두 함수 테스트를 진행했습니다. 
- 각각 debounce, throttle이 잘 작동하는지 timer로 테스트 했습니다.
- 추가로 default delay 값에 대한 부분도 테스트 했습니다.
- 처음 테스트 코드를 작성해봐서 혹시 부족한 점이 있다면 편하게 말씀해주시면 감사하겠습니다!!
> [view] debounce, throttle 테스트 코드 작성

- packages/vscode/src/boot/yoongja/llm.ts
- packages/vscode/src/boot/yoongja/test-llm.ts
request :     'This is test of the project, How can I turn on this project? do you know githru? Please answer in one word.';
respond: Yes.
open ai , api 연동
- open ai api키를 사용하여 연동하였습니다.
- 다음 과정은 prompt에 githru의 commit요약기능을 만들도록 prompt에 어떠한 정보들을 담아서 보낼지 고려해야합니다.
> [vibe] llm이용 요약 api연결

- .github/CODEOWNERS
- package.json
- packages/analysis-engine/package.json
- packages/view/package.json
- packages/vscode/README.md
- packages/vscode/package.json
> env: ready for v0.8.0

- packages/view/CONTRIBUTING.md
Closes #882, #879 
문서 내 오탈자와 부적절한 예시를 수정하였습니다.
> [docs]: view/CONTRIBUTING.md 파일 수정

- packages/mcp/README.md
README 수정
영어로 변환 및 README 수정
- 영어로 처리
- README 수정
> README 수정 및 영어로 변환.

- packages/mcp/package.json
- packages/mcp/src/common/types.ts
- packages/mcp/src/html/contributors-chart.html
- packages/mcp/src/html/error-chart.html
- packages/mcp/src/html/no-contributors.html
- packages/mcp/src/server.ts
- packages/mcp/src/tool/contributorRecommender.ts
> FEAT(vibe): [MCP Tool] 리뷰어 추천 툴 차트 템플릿 표현

- packages/view/index.ts
- packages/view/package.json
- packages/view/tsconfig.json
#923 
npm publish 를 통해 패키지 배포를 진행
> feat(view): mcp tool 연동용 컴포넌트 배포

- packages/mcp/src/server.ts
MCP 패키지에서 사용하지 않는 import를 제거하였습니다.
> refact: 안쓰는 import 제거

- packages/view/index.ts
- packages/view/package.json
- packages/view/tsconfig.json
Reverts githru/githru-vscode-ext#933
> Revert "feat(view): mcp tool 연동용 컴포넌트 배포"
