packages/view/src/components/Detail/Detail.tsx, packages/view/src/components/Detail/Detail.util.ts, packages/view/src/types/NodeTypes.temp.ts
- close #70 
- enhance(view): add Commit Type Message Property closed [#70]
commit type에 message 추가하였습니다.
- enhance(view): CommitNode Type add taskId Property
commitNode Type에 taskId추가하였습니다.
taskId를 통해 동일 Cluster 내부 Commit 을 찾을 수 있는데, Detail Component에 해당 Commit들을 나타내줘도 좋을 것 같지만, 무슨 의미가 있나 싶긴한데 얘기를 나눠보고 싶어요.
혹시 몰라 추가했습니다.
- feat(view): Detail Component
scss 작성하지 않고 해당 ui template만 작성해서 commit 남겼습니다.
=> feat(view): Detail Component 

packages/view/.eslintrc.json
react-hooks eslint rule이 빠진 듯 하여 올립니다.
'exhaustive-deps' rule같은 경우는 매우 쓸만한 놈이기도 해서 추가하였습니다.
혹시 view팀에서 hooks rule을 쓰지 말자라고 기존에 약속한게 있다면 살포시 "안써요~" 라고 답변 남겨주세요.
=> setup: set react-hooks eslint rules

packages/view/public/fake-assets/sampleClusterNodeList.json, packages/view/src/components/Detail/Detail.tsx, packages/view/src/components/Detail/Detail.util.ts, packages/view/src/types/NodeTypes.temp.ts
Before this commit, Detail Components contents showed the contents of one target commit, but after this commit, it shows the commit list in cluster
- Target_ID => TARGET_TASK_ID 변경
- getTime Func Delete
- scss
- Commit 상세 내용 추가
---
[ fix(view): fix value naming taskId => ClusterId ]
- taskId 대신 ClusterId 적용
[ enhance(view): add Cluster Detail Data in Detail Component ]
- add Detail Data 
- authors
- commits
- files
- insertions
- deletions
=> enhance(view):  Detail Component Contents

packages/view/src/components/TemporalFilter/ClocLineChart/ClocLineChart.tsx, packages/view/src/components/TemporalFilter/TemporalFilter.util.ts
cloc 차트를 구현하였습니다.
차후 수정해야할 부분을 주석의 TODO로 정리 해두었습니다.
민정님과 같이 수정할 예정입니다! @kmin-jeong
=> feat(view): add cloc linechart

packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.const.ts, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.scss, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.tsx, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.type.ts, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.util.ts, packages/view/src/components/VerticalClusterList/Summary/Summary.scss
5fcc7dc60d734860fd6a54bd04bfb1661ae8b22a
- ClusterSize에 따라 height를 다르게 했던 ClusterGraph v1을 삭제하고, height는 고정시키고 내부에 rect를 추가하여 내부 rect의 width를 통해 ClusterSize를 표현하는 v2를 추가했습니다.
c816fc53e7fc75f98a8819e9f2f41d3d4d4861d0
- d3의 style attributes를 scss 파일로 분리하는 작업을 수행했습니다.
e93f8eab3c57a068f3df365b9be2aec7f4efbded
- ClusterGraph에서, 하나의 ClusterElement를 hover 했을 때 stroke-width가 증가하는 액션을 추가했습니다.
ef8d7a300795151ef1bbf959b76b10b7e476ed66
- useEffect 내부에 존재하던 d3 graph draw 로직을 컴포넌트 외부로 분리했습니다.
- graph destroy 로직을 추가하여, 데이터 변경 시 기존 View를 삭제하도록 구현했습니다.
6ac0f1a17410da5aa301d56d21a750abc5ef70ab
- Cluster Click 이벤트 핸들러를 등록했습니다.
ba26cb5dd7dc570c8365ae0d8163fb10c8a9d81b
- githru를 참고하여 ClusterSize에 대한 시각화 scale을 수정했습니다.
- githru에서 ClusterGraph의 scale을 나타낼 때, ClusterSize (cluster에 포함된 commit 개수) 가 10이상이면 …
=> feat(view): add ClusterGraph Component v2 in VerticalClusterGraph

packages/view/src/App.tsx, packages/view/src/components/Detail/Detail.tsx, packages/view/src/components/Detail/Detail.util.ts, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.tsx, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.util.ts, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.const.ts, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.tsx, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.type.ts, packages/view/src/components/VerticalClusterList/Summary/AuthorName/AuthorName.tsx, packages/view/src/components/VerticalClusterList/Summary/AuthorName/index.ts, packages/view/src/components/VerticalClusterList/Summary/Summary.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.util.ts, packages/view/src/components/VerticalClusterList/VerticalClusterList.tsx, packages/view/src/components/VerticalClusterList/VerticalClusterList.util.ts, packages/view/src/types/global.ts
6b99c2188254e6d05fcc4d0b3fff3dbe74990b05
- Summary 클릭 시 setSelectedData 상태 변경 함수를 통해 selectedData 상태를 변경합니다.
- clusterId를 통해 해당하는 Cluster를 필터링하는 유틸 함수를 추가했습니다.
67670e10a4297a1db85d5dee4b6327ef44a40e82
- selected cluter ID로 2435를 고정으로 사용하던 Detail에서, 상위 컴포넌트로부터 selectedData props를 전달받아 적용했습니다.
a5168220b81765fb0d87cb7a8e7f3ef5772b0ad2
- ClusterGraph의 Cluster element 클릭 시 selectedData 상태 변경이 일어나도록 구현했습니다.
8cd0955dc1daa57e97db18c79cde94fde199f612
- Detail 컴포넌트의 위치를 View 하단에서 Summary 컴포넌트 하위로 이동시켰습니다.
=> feat(view): add opening Detail Component action of selected cluster event

packages/view/src/components/Detail/Detail.tsx, packages/view/src/components/Detail/Detail.util.ts, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.scss, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.tsx, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.util.ts, packages/view/src/components/TemporalFilter/TemporalFilter.scss, packages/view/src/components/TemporalFilter/TemporalFilter.tsx, packages/view/src/components/VerticalClusterList/Summary/AuthorName/AuthorName.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.scss, packages/view/src/components/VerticalClusterList/Summary/Summary.tsx, packages/view/src/components/VerticalClusterList/VerticalClusterList.tsx
- #58 
- metric 변경 시 transition 추가 (a147d8cc4f67d152bcf303784010b88af68350a8)
- 툴팁 추가 (b1c6ee16ecc31bd10272aeccc400584f4a771a7c)
- 데이터 10개 초과 시 최대 10개만 렌더되도록 갯수 제한 (ea74c58ceb94804130a57f768f69ec55f6764086)
- author name y축 세부 위치 조정 (a147d8cc4f67d152bcf303784010b88af68350a8)
- bar class 내 text와 rect 그룹화 및 hover 스타일 변경 적용 (b80568d665272ee74d7b20f16e8752d0a71edfec)
- scss 네이밍 수정 및 nesting 적용 (a4950e668cc266cedba346a611563e50843ed2be d4e3028cc67327d4ffe988c9daadcfaeb4ca6e06)
- rebase 후 `Summary` 내 unique key prop error 해결 (136b3d3469328b2930dc8fce92b91cd6b54e25b8)
=> feat(view): add tooltip and transition to AuthorBarChart

packages/analysis-engine/src/csm.spec.ts, packages/analysis-engine/src/csm.ts, packages/analysis-engine/src/types/CSM.ts
CSM 생성에 대한 구현입니다.
master STEM 을 기준으로 루트노트부터 순회하여 머지커밋에 연결된 커밋들을 squash 합니다.
CSM 생성 인터페이스는 아래와 같습니다. 
input : `Map<string, CommitNode>`, `Map<string, Stem>` 
output : `CSMDictionary`
---
example commit log : 
```
master = [0, 1,              2,                 3, 4, 5]
sub1 =         [6,7,       8,  9,10,         11]
sub2 =              [12,13,         14,15,16]
```
example output (CSMDictionary) :
```typescript
{
master: [
{
base: { commit: { id: '0', parents: [], branches: [] }},
source: []
},
{
base: { commit: { id: '1', parents: [ '0' ], branches: [] }},
source: []
},
{
base: { commit: { id: '2', parents: [ '1', '8' ], branches: [] }},
source: [
{ commit: { id: '6', parents: [ '1' ], branches: [] } },
{ commit: { id: '7', parents: [ '6' ], branches: [] } },
{ commit: { id: '12', …
```
=> feat(engine): implement csm

packages/analysis-engine/src/types/index.ts
engine 패키지 내 type 들을 index.ts 를 통해 접근할 수 있도록 구성합니다.
=> chore(engine): re-export types via index.ts

packages/analysis-engine/src/stem.spec.ts
closed #116 
- fakeCommits 배열을 CommitRaw 배열로 변환하는 과정에서, 배열의 인덱스 값으로 sequence 값이 할당되도록 수정했습니다.
- stem 테스트에서 sequence 값이 중요하지 않기도 하고, 
- fakeCommits 배열 각 요소에 sequence 값을 직접 넣어주면 이후에 테스트 데이터가 추가될 때 일일이 수정해주기 번거로울 것 같아 직접 넣지 않았습니다.
- fakeCommits의 id 값을 해시 값이 아닌 알파벳 순으로 지정했습니다.
- 기존의 실제 커밋 해시 값은 알아보기 너무 어려운 것 같아 알파벳으로 수정했습니다. (그림도 함께 수정했습니다.)
- 넘버링의 경우 sequence 값과 혼동될 것 같아 알파벳을 사용했습니다.
=> test(engine): add sequence to fake commits

packages/vscode/src/webview-loader.ts
- `isProduction = false;`로 처리가 되어 있어서 vscode extension의 view가 mocking data로 rendering이 되고 있습니다.
- 차후 process.env === 'production'와 같은 flag로 처리하는 것도 한 방법일 것 같아 보입니다.
=> fix(vscode): activate production mode

packages/view/public/fileChanges.json, packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.tsx, packages/view/src/components/Statistics/FileIcicleSummary/index.ts, packages/view/src/components/Statistics/Statistics.tsx
FileIcicleSummary는 커밋 클러스터별 변경된 파일을 icicle tree 형식으로 제공하는 컴포넌트입니다.
데이터 가공쪽은 다른 컴포넌트 작업되면 진행하는것이 효율적일거서 같아서 미리 작업하지는 않았고 임시 데이터를 fileChanges.json이라는 파일로 추가하여 사용했습니다.
fileChanges.json은 githuru - FileIcicleSummary.js >line 57의 fileAnalyzer.getFileStructure() 결과값을 복사한 값입니다. [코드 링크](https://github.com/githru/githru/blob/b479984a3081e4e6e389179b86a6997db984d5a3/frontend/src/components/FileIcicleSummary.js#L57)
코드가 들어갈 파일을 생성했습니다.
파일 위치는 같은 Statistics 컴포넌트인 AuthorBarChart 위치와 동일하게 Statistics 하위에 만들었습니다.
데이터 기반으로 IcicleTree를 그립니다.
https://observablehq.com/@d3/zoomable-icicle 를 참고했습니다.
width, height는 각각 600, 400으로 임의로 정했습니다.
차트 그리는 부분은 githru-tutorial에서 진행한 내용과 크게 다르지 않아서 영어 주석이 부족하신 경우 https://github.com/githru/githru-feature-practices/pull/18#issue-1315908433 PR 내용도 함께 봐주시면 좋을것 같습니다. …
=> feat(view): add FileIcicleSummary

packages/view/src/components/Detail/Detail.const.ts, packages/view/src/components/Detail/Detail.hook.tsx, packages/view/src/components/Detail/Detail.scss, packages/view/src/components/Detail/Detail.tsx, packages/view/src/components/Detail/Detail.util.ts, packages/view/src/components/VerticalClusterList/Summary/Summary.scss, packages/view/src/components/VerticalClusterList/Summary/Summary.tsx
- closed #68 
[fix(view): fix Detail Util Func Smallize](https://github.com/githru/githru-vscode-ext/commit/20628c4e90b414f8496090bf96c5f8065f3232dc)
- [taejs review](https://github.com/githru/githru-vscode-ext/pull/88#issuecomment-1239540340) 를 참고하여 util 함수를 리펙토링하였습니다.
[style(view): add Detail css](https://github.com/githru/githru-vscode-ext/commit/134313937b1b27037d2d249938456d8cca869e29)
- 간단한 Detail Component css 추가하였습니다.
[style(view): add Detail Container css in Summary](https://github.com/githru/githru-vscode-ext/commit/0191d8b14b20b2bb08883c09dc4f8db5414152e1)
- Summary에서 Detail Component를 사용하기에 Detail Component의 Container에 대한 css를 추가하였습니다.
Style에 대해 큰 적용은 없지만 
Color 관련해서 git insight를 참고하다보니 githru에서 정한 color와 결이 다른느낌이 듭니다.
이대로 독단적인 color를 사용해도 되는지 궁금합니다.
=> style(view): add Detail Component css

packages/analysis-engine/src/csm.ts
CSM 생성시, squash 대상 내 머지커밋 식별 로직을 아래와 같이 변경했습니다.
```
1) 현재 stem 의 루트노트부터 순회 시작
2) 머지커밋 여부 확인
- parents.length > 1 일때
3) 머지커밋 stem 으로 따라올라가기
- parents 중 현재 stemId 와 다른 stem 필터링
4) 머지커밋 stem 에서 squash 대상 잘라내기
- spliceIndex + spliceCount 계산
- splice
5) squash 대상에서 머지커밋여부 확인하기
- 2와 동일
6) 3,4,5반복
```
```typescript
// ...
{
base: {
commit: {
sequence: 95,
id: 'fd46b07926bce8745ebe83d0a66dd05fb1b4613a',
parents: [
'd9483784b6b946ee6fb4e2c83f4b554c753ab632',
'3af7bc61a73bd044d5b9be7d8252ab3e21489284'
],
branches: [],
tags: [],
author: {
name: 'Parksunghyeon',
email: '79688915+pshdev1030@users.noreply.github.com'
},
authorDate: 'Sun Sep 4 01:24:24 2022 +0900',
committer: { name: 'GitHub', email: 'noreply@github.com' },
committerDate: 'Sun Sep 4 01:24:24 2022 +0900',
message: 'Merge pull request #75 …
```
=> fix(engine): bugfix idendtifing nested-merge from squash-commits (#126)

packages/view/src/components/TemporalFilter/ClocLineChart/ClocLineChart.scss, packages/view/src/components/TemporalFilter/ClocLineChart/ClocLineChart.tsx, packages/view/src/components/TemporalFilter/CommitLineChart/CommitLineChart.scss, packages/view/src/components/TemporalFilter/CommitLineChart/CommitLineChart.tsx, packages/view/src/components/VerticalClusterList/VerticalClusterList.scss, packages/view/src/styles/_reset.scss
- 초기 레이아웃 깜빡임 관련 CLS 성능 개선 (7aa9862ccf25d0b10321d88515b4f65bd9c1d499)
| | AS-IS | TO-BE| 
| :---: | :---: | :---: |
| 화면 | ![ezgif com-gif-maker-6](https://user-images.githubusercontent.com/69497936/189528013-2dae1921-d53f-48f1-a911-cea64f81423a.gif) | ![ezgif com-gif-maker-4](https://user-images.githubusercontent.com/69497936/189527896-00e8584b-0561-4d35-961d-597b1a4b10e6.gif)|
| Lighthouse <br />측정 | <img width="927" alt="스크린샷 2022-09-11 오후 10 17 00" src="https://user-images.githubusercontent.com/69497936/189529752-3fb92204-d390-41a1-bc9f-5d2b3ff6f61a.png"> | <img width="926" alt="스크린샷 2022-09-11 오후 10 17 48" src="https://user-images.githubusercontent.com/69497936/189529756-0627fe73-bef2-4475-b1f5-75982c2a3503.png"> |
| Performance | 85 | 93 |
| CLS | 0.233 | 0.059 |
<br …
=> fix(view): improve CLS performance

packages/view/src/App.scss, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.const.ts, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.scss, packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.scss, packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.tsx, packages/view/src/components/Statistics/Statistics.scss, packages/view/src/components/VerticalClusterList/VerticalClusterList.scss, packages/view/src/styles/_reset.scss
- 전반적 레이아웃 100%에 맞게 축소 (5af00a869b326483d531bad7170c5488de7884f0)
- 100% 시 화면 레이아웃에 모든 컴포넌트가 보이지 않는 문제 존재
- 아래 영진님께서 전달해주신 css 바탕으로 기존 전체 컴포넌트 통합 시 레이아웃 크기가 영역을 벗어나는 부분 수정하였습니다.
```
.middle-container {
height: calc(100vh - 200px);
}
// 하위 컴포넌트
height:100%
height:50%
```
- 반응형이 정확히 적용된 것이 아니라 혹시 수정할 부분 있다면 말씀주시면 감사하겠습니다
| AS-IS | TO-BE | 
| :---: | :---: |
| <img width="1020" alt="스크린샷 2022-09-12 오전 12 15 47" src="https://user-images.githubusercontent.com/69497936/189535253-41ae348e-dc16-4c58-b192-440b377dc6a2.png"> | <img width="1019" alt="스크린샷 2022-09-12 오전 12 16 31" src="https://user-images.githubusercontent.com/69497936/189535250-696af41b-b31b-4a8a-89e0-23b78c6b7e25.png"> |
<br />
<br />
cf.  기존 `AuthorBarChart`에만 적용된 background-color를 transparent로 변경 후 …
=> style(view): fix authorBarChart layout sizes 

packages/analysis-engine/src/stem.spec.ts, packages/analysis-engine/src/stem.ts
`commit 32a79953002b7f1aa30e56900cfc38a0fcb27287 (HEAD -> main, upstream/main, upstream/HEAD, origin/main, origin/HEAD)`
HEAD가 main 브랜치에 있을 때는, 브랜치 순서 상에서 main이 가장 앞에 있고
```
commit 5609877533d0c6e9aae6e23f01981ebb056fe2a1 (HEAD -> test-vscode)
Author: ooooorobo <orobos654@gmail.com>
Date:   Sun Sep 11 22:48:06 2022 +0900
a
commit 32a79953002b7f1aa30e56900cfc38a0fcb27287 (upstream/main, upstream/HEAD, origin/main, origin/HEAD, main)
Author: Paul An <anpaul0615@gmail.com>
Date:   Sun Sep 11 22:22:36 2022 +0900
```
HEAD가 다른 브랜치에 놓여 있을 때는 브랜치 순서 상에서 main이 맨 앞에 있지 않습니다.
그런데 stemDict의 key는 branches[0]으로 설정되어서,
두번째 상황에서는 stemDict의 키로 main이 아니라 upstream/main이 들어가고 있습니다.
(stem.tsL84)
commitRaw.branches 배열에서 main/master/HEAD 브랜치의 idx 위치에 관계 없이, branches 배열에 존재한다면 그것을 stemId로 사용해야 합니다.
(+)
원래는 …
=> fix(engine): main/master/HEAD 브랜치를 가질 경우 stemId를 main/master/HEAD로 설정

packages/vscode/src/webview-loader.ts
webview를 loader할때 root 태그에 적용한 스타일로 인해서 temporal filter가 scroll bar를 덮는 문제를 수정했습니다.
| AS-IS | TO-BE | 
| :---: | :---: |
| <img width="700" alt="스크린샷 2022-09-12 오전 12 15 47" src="https://user-images.githubusercontent.com/81841082/189560792-f42cfdd8-1c6c-469c-a1f4-2c4801a7c8ff.png"> | <img width="700" alt="스크린샷 2022-09-12 오전 12 16 31" src="https://user-images.githubusercontent.com/81841082/189560759-5c2c93db-13c6-4925-83e4-0d0d84d91919.png"> |
Hotfix로 포함해야할지 모르겠어서 마일스톤 v0.2.0로 우선은 분류해놓았습니다.
=> fix(view): fix tempral filter overlap scroll bar

packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.const.ts, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.scss, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.tsx, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.type.ts, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.util.ts, packages/view/src/components/VerticalClusterList/Summary/Summary.scss
b9cc3a44d20b15fe89e047b16f91aed47b543f39
- selectedData 변경 시 Detail 컴포넌트가 보여질 때 ClusterGraph에 transition 추가했습니다.
- 컴포넌트 렌더링시에 svg가 매번 리렌더링 되기 때문에, transition을 적용하기 위해선 이전 selectedIndex 값을 기억하고 있어야 합니다.
- 그렇기 때문에 useRef를 통해 이전 selected 값을 기억하도록 하고, d3의 draw 작업이 마무리되면 현재 selected 값을 selectedPrev에 저장합니다.
- 이후 해당 값을 data로 넘겨 초기 위치는 이전 selected를 기반으로, 이어지는 transition은 현재 selected 값을 기준으로 발생하도록 구현했습니다.
0ea3fc758dc429a8dc0685587e84393223cb3f7d
- ClusterGraph 의 className들을 컨벤션에 맞게 수정했습니다. (ex. cluster-graph_container)
27ae411a72ca5ab78eaf3e7d6aba42f2e3f520ab
- summary 컴포넌트에 Detail이 펼쳐지는 transition을 적용했습니다.
- Detail의 open transition과 close transition이 동시에 일어날 때, ClusterGraph와 싱크가 맞지 않는 문제가 있기 때문에 clusterGraph와 Summary의 close transition을 삭제했습니다.
7466762ecedaed3369a65b76951a1d0871a07cc2
- detail …
=> feat(view): add transition in ClusterGraph

packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.const.ts
af6a9f2534193f60f2e8e3c90517c143b37d4294
- #146 의 VerticalClusterGraph size 수정 작업을 수행했습니다.
- 기존 size는 width : height이 100 : 50 으로 2 : 1 비율이었고, 이를 40 : 80 으로 수정했습니다. (35 : 70은 너무 작음)
- ClusterGraph 만 적용했고, 지혜님 작업과 병합할 예정입니다.
| AS-IS | TO-BE | 
| :---: | :---: |
| <img width="1020" alt="스크린샷 2022-09-12 오전 12 15 47" src="https://user-images.githubusercontent.com/49841765/189594114-9e668162-d9a8-445c-b25f-83bd427706fb.png"> | <img width="1019" alt="스크린샷 2022-09-12 오전 12 16 31" src="https://user-images.githubusercontent.com/49841765/189594204-51969399-f1c4-4d91-83ca-68403ace5126.png"> |
=> fix(view): update cluster graph size (width, height, gap)

packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.scss, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.tsx, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.type.ts, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.util.ts
a9e557f5c206caaa1c62262c0cc447ddabb7cfd1
- 다음 작업을 수정했습니다. 
>node 색깔도 조금 명확하게 바꾸는게 좋겠습니다. 어두운 바탕이라 그런지 잘 안보이네요.
>윗 node와 아래 node가 서로 연결된 느낌이 없어서, node와 node사이에 link (수직선?)을 넣어주던지, 혹은 아예 테이블 형태처럼 붙여주세요. 서로 이어져서 ordering되었다는 인식이 되어야 합니다.
- g element 외부에서 line element 를 추가하여 각 Node를 이어주었습니다.
=> feat(view): add cluster link line in ClusterGraph (fix issue #146)

packages/view/src/App.scss, packages/view/src/App.tsx, packages/view/src/components/Detail/Detail.tsx, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.scss, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.tsx, packages/view/src/components/Statistics/Statistics.scss, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.scss, packages/view/src/components/VerticalClusterList/VerticalClusterList.hook.ts, packages/view/src/components/VerticalClusterList/VerticalClusterList.scss, packages/view/src/styles/_reset.scss, packages/view/src/utils/time.ts
- #147 
- 멘토님께서 언급해주신 부분 수정 (8760d1143980c564749b77f818c185f51d747d01 cbdb8a00e95d597e25e7c5570f0c1364f143d389 e8639fb97ba50cfa1e2680776e01072eb8db1b20)
>  1. 윗쪽 select box에서 commit을 commit #로 바꿔주세요.
>  2. select box의 테두리만 굵은데 나머지와 통일성 있게 바꿔주시고,
>  3. select box 위치를 오른쪽 위로 바꿔주세요.
>  4. select box와 chart, 아래 축 정보의 margin을 줄여주세요.
>  5. y축의 tick은 없어도 되겠습니다.
- 전반적인 레이아웃 수정
- Statistics에 padding 추가
- middle-container 중앙에 위치하도록 수정
- 스크롤바 스타일 수정 (bdc46c369e9762cd8fdd61b7ec070c231d50a623)
- 기존 전반적 스타일과 통일감 없이 튀는 스크롤바 스타일 통일감 있게 변경
- AS-IS
- TO-BE
=> style(view): fix style issues in authorBarChart

packages/view/src/components/Detail/Detail.scss, packages/view/src/components/Detail/Detail.tsx, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.scss, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.tsx, packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.tsx, packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.util.ts, packages/view/src/components/TemporalFilter/ClocLineChart/ClocLineChart.scss, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.scss, packages/view/src/components/VerticalClusterList/Summary/Summary.scss, packages/view/src/components/VerticalClusterList/Summary/Summary.tsx, packages/view/src/styles/_reset.scss, packages/view/src/utils/index.ts
- #146 
- #154 
- css class 네이밍 BEM 컨벤션으로 수정
- 최상위 감싸는 컴포넌트 네이밍 `container`로 통일 (기존 wrap, wrapper, entire 등 혼재)
- Summary 컴포넌트 내 불필요한 depth 및 조건문 제거
- 전반적인 Detail 컴포넌트 스타일 수정
- Detail 컴포넌트 내 [text ellipsis 이슈](https://github.com/githru/githru-vscode-ext/pull/154) 해결
- 커밋 해시 6자리로 수정
- 컴포넌트 간 padding 및 margin 조절
- more commit count 내용 아이콘 옆으로 이동
- more 버튼 hover 시 색 추가
- 스크롤바 때문에 내용이 밀려나는 이슈 해결
| AS-IS | TO-BE |
|:---:|:---:|
|<img width="800" src="https://user-images.githubusercontent.com/69497936/189802779-908ccf04-a98f-4551-9a4e-bcb4a3845f6f.png">|<img width="800" src="https://user-images.githubusercontent.com/69497936/189802946-a32ea377-089a-4406-9d25-1edb321d1a84.png">|
|![ezgif com-gif-maker-8](https://user-images.githubusercontent.com/69497936/189803499-ef0f13a7-2ff1-4537-8943-10e792a8 …
=> style(view): fix style issues in detail component

packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.scss, packages/view/src/components/VerticalClusterList/Summary/Summary.tsx
82539a72e6a515d6178b17e4d691ec60713bfd96
- https://github.com/githru/githru-vscode-ext/pull/154#pullrequestreview-1104405275 에서 언급된 문제를 개선했습니다.
- 하지만, height가 결정된 이후에 다시 한 번 변경되는 작업을 거쳐야만 가변 길이 transition이 동작하기 때문에, 완벽히 개선하지는 못했습니다.
- summary-detail__container와 detail 컴포넌트 사이에 transition이 발생하지 않는 div 태그를 추가하여 height 값이 한 번만 변경되어 resizeObserver가 감지할 수 있도록 수정했습니다.
14091cee368a3e543e0a8b9a1ddf2cfe73a2c075
| AS-IS | TO-BE | 
| :---: | :---: |
| <img width="400" alt="스크린샷 2022-09-12 오전 12 15 47" src="https://user-images.githubusercontent.com/49841765/189832692-f59cd20b-83d6-47b0-8aff-2b6fbd0bc153.gif"> | <img width="400" alt="스크린샷 2022-09-12 오전 12 16 31" src="https://user-images.githubusercontent.com/49841765/189832732-8feb136f-6018-46d5-81fa-d326bde0321c.gif"> |
- Summary에서 …
=> fix(view): modify variable height ClusterGraph transition & update scroll

packages/view/src/components/VerticalClusterList/Summary/Summary.scss
- #159 
> git graph를 참조해본 결과, 어떤 detail이 열리든 scroll 가운데로 고정하는 방식을 택했었고, 이를 반영해보았습니다. (@vgihan)
- summary heigth 고정
- 기존 기한님이 참고하신 git-graph 토대로 height 고정
- 추가 마우스 움직임 없이 다음 클러스터 연속으로 확인 가능 및 화면 정중앙에 위치
- 클러스터 클릭시 animation 제거
- 기존 summary 내 animation 최적화 되어 있지 않아 toggle되며 겹쳐지는 문제 존재
(추후 작업 시 다시 복구 예정일지 몰라 일단 주석 처리해두었습니다.)
- AS-IS
- TO-BE
=> feat(view): fixed summary height and delete animation

.gitignore, package-lock.json, packages/analysis-engine/package.json, packages/analysis-engine/tsconfig.json, packages/view/src/components/TemporalFilter/TemporalFilter.scss, packages/vscode/.vscodeignore, packages/vscode/LICENSE, packages/vscode/package.json, packages/vscode/src/extension.ts, packages/vscode/src/utils/NodeTypes.temps.ts, packages/vscode/src/utils/csm.mapper.ts, packages/vscode/src/webview-loader.ts
vscode를 띄울 때, 개발중인 path(extensionPath)를 바라보게 하지 않고,
현재 열려있는 workspace folder의 첫번째의 git 을 바라보게 만들었습니다.
(vscode가 multiworkspace를 지원하기 때문에)
+ publish ready 추가합니다.
=> fix(vscode): read git of current opened workspaced folder

packages/analysis-engine/src/parser.ts
- 기존에 `HEAD -> main` 으로 표기된 정보에 대해서 "main"만 branch정보로 포함하는 것이 아닌, HEAD도 같이 포함하도록 수정
- https://github.com/githru/githru-vscode-ext/issues/169
- splitedCommitLine[1]에 대해서(1) branchAndTagInfos로 전환하는(2) 예시
=> fix(engine): include HEAD info from the parser

packages/analysis-engine/src/parser.ts
parser.ts 의 개행문자 오타를 수정했습니다. `/n` -> `\n`
@jejecrunch 님, Summary.util.ts 파일에 있는 '/n'은 이 작업이 머지되면 후속으로 처리하실 예정이실 것 같아서 따로 작업하지 않았습니다. 혹시 더 작업이 필요한 부분이 있다면 알려주세요.
closed #215
=> fix(engine): fix typo in newline escape seq

packages/view/src/App.scss, packages/view/src/components/VerticalClusterList/VerticalClusterList.scss
- closed https://github.com/githru/githru-vscode-ext/issues/206
- WebView의 width가 줄어들게 되면, line chart와 하위 컴포넌트들이 충돌되는 문제 발생합니다.
- line chart의 height이 정해져있지 않아 내부 컴포넌트의 높이가 가변적으로 변하는 상황이 발생하여 200px로 고정시킴
- 추가로 ClusterGraph가 잘리는 문제가 발생합니다. 일정 width 이하로 줄여지지 않게 구현할 수 있고, width를 줄이더라도 line chart와 충돌이 없도록 수정이 필요합니다.
-  Cluster Graph svg의 width를 84px로 지정했으나, container의 width가 줄어듬에 따라 svg의 width또한 줄어들게 되었음
=> min-width를 84px로 설정하여 깨짐을 방지하였음.
=> style(view): Cluster Graph , Line Chart 반응형 개선 작업

packages/analysis-engine/src/csm.spec.ts, packages/analysis-engine/src/csm.ts, packages/analysis-engine/src/index.ts, packages/analysis-engine/src/stem.spec.ts, packages/analysis-engine/src/stem.ts
closed #144 
파라미터로 전달된 branch 이름을 기준으로 Stem과 CSM을 생성하도록 `build{Stem/CSM}Dict` 함수를 변경합니다.
'dev' 브랜치를 기준으로 생성한 경우
```js
const stemDict = {
dev: [a, b, c, j, k, l, m],
main: [d, e, f],
head: [n, o],
'implicit-1': [g, h, i]
}
const csmDict = {
'dev': [
{ base: a, source: [] },
{ base: b, source: [] },
{ base: c, source: [g] },
{ base: j, source: [] },
{ base: k, source: [] },
{ base: l, source: [] },
{ base: m, source: [] },
}
```
sub1 브랜치를 기준으로
```js
const stemDict = {
sub1: [0, 1, 6, 7, 8, 9, 10, 11],
sub2: [12, 13, 14, 15 ,16],
main: [2, 3]
}
const csmDict = {
'sub1': [
{ base: 0, source: [] },
{ base: 1, source: [] },
{ base: 6, source: [] },
{ base: 7, source: [] },
{ base: 8, source: [13, 12] },
{ base: 9, source: [] },
{ base: 10, source: [] },
{ base: 11, source: [16, 15, 14] },
``` …
=> feat(engine): build stem & CSM based on passed branch name

packages/view/src/components/Detail/Detail.scss, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.tsx, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.util.ts, packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.const.ts, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.scss, packages/view/src/components/VerticalClusterList/Summary/Summary.tsx, packages/view/src/components/VerticalClusterList/VerticalClusterList.scss
- close #205 
- #209
- close #218
-  **cluster graph에만 css 적용되도록 className 지정 (e1a6891c356617de234938fc852a30ba819016de)**
이전 #209에서 적용된 css가 summary 내 아이콘에도 함께 적용되어 밀려난 이슈 해결
- **author bar chart x축 scale 수정 (04fe14cf1e95503c9f19f8711fbe139db5d17b40 ffb1df2800195edb9a8ce099b4e305410d773ff0 f5e7dae4a6e1a3efd2aca1748be96d4b77b588fd)**
>Related Issue
https://github.com/githru/githru-vscode-ext/issues/147
Content
y축 값이 지금은 commit # / Total commit# 의 백분율인데, 이럴 경우 현재처럼 차트의 반 이상이 비어 있게 됩니다 (dominant한 contributor가 있지 않는 이상). 100%를 max로 잡지말고 최대값+a를 max로 잡거나, 혹은 그냥 cardinality (commit#)만 가지고 표시하면 더 보기 좋을 것 같습니다. (추후에 값의 분포에 따라서 top 10 user만 보여준다던지, Percentage가 서로 비슷할 경우, 다를 경우를 분리해서 보여주는 값을 다르게 한다던지 하는 방법도 있겠네요) 
| | AS-IS | TO-BE |
| :---: | :---: | :---: |
| x축 scale 변경해 <br/>차트의 반 이상 비어있는 이슈 해결 …
=> feat(view): change author bar chart x axis scale and apply responsive layout to `summary` component

packages/vscode/package.json, packages/vscode/src/extension.ts, packages/vscode/src/setting-repository.ts
setting에 GitHub token 값을 저장하고, 불러올 수 있는 feature 추가합니다.  #228
=> feat(vscode): add github token from settings (#228)

packages/view/CONTRIBUTING.md, packages/view/src/components/Detail/Detail.tsx, packages/view/src/components/Detail/Detail.type.ts, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.tsx, packages/view/src/components/Statistics/Statistics.tsx, packages/view/src/components/Statistics/Statistics.type.ts, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.tsx, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.type.ts, packages/view/src/components/VerticalClusterList/Summary/AuthorName/AuthorName.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.type.ts, packages/view/src/components/VerticalClusterList/VerticalClusterList.tsx, packages/view/src/components/VerticalClusterList/VerticalClusterList.type.ts, packages/view/src/types/global.ts
[#175 ](https://github.com/githru/githru-vscode-ext/issues/175)
Compenent props들이 Component 안에 같이 존재했습니다.
대부분의 Component props를 분리하고 리팩토링했습니다.
다른 곳에서 쓰이지 않는 props type이라면 해당 컴포넌트의 type 파일로 분리해두었습니다.
혹시 안좋은 패턴이 있거나 의도하셨는데 제가 고친 부분이 있다면 편히 말씀해주세요 !
=> refactor(view): modify and add components props

packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.const.ts, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.tsx, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.type.ts, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.util.ts, packages/view/src/components/VerticalClusterList/Summary/Summary.tsx, packages/view/src/components/VerticalClusterList/VerticalClusterList.tsx
- https://github.com/githru/githru-vscode-ext/issues/226
293ef890ec8c3dbeff64839579b0acde4269fb37
- `{behavior: "smooth"}` option 추가를 통해 Detail이 펼쳐질 때 스크롤이 부드럽게 펼쳐지도록 개선했습니다.
29357850e5bb7ecbafa9ad03166e3a7103d2f1a8
- @hanseul-lee 님의 의견을 바탕으로 ClusterGraph에서 Detail이 펼쳐질 때 펼쳐지는 방향을 개선했습니다.
- 기존 ClusterGraph에서는 현재 선택된 cluster에서 아랫쪽 cluster가 열리든 위쪽 cluster가 열리든, 모든 open transition이 위에서 아래 방향으로 펼쳐졌습니다.
- 하지만, 아랫쪽 cluster가 펼쳐질 때는 ClusterGraph가 아랫쪽에서 위쪽으로 펼쳐지는 transition을 적용함으로써 좀 더 자연스러운 transition을 부여하고자 했습니다.
**Problem**
- d3 + react를 사용하는데 있어서, d3의 draw 로직을 모두 useEffect hook에서 진행하고, cleanup 시에 destroy 하기 때문에 기존에 그려진 d3 element를 기억하지 못하고 deps의 변경이 있을 때마다 다시 draw 하게 됩니다.
- d3로 transition을 부여하기 위해선, 기존에 그려진 d3 element를 바탕으로 transition() function을 통해서 부여하게 되는데, 앞서 언급한 것과 같이 d3 element를 destroy …
=> fix(view): modify logic of chart transition in VerticalClusterList

packages/view/src/App.tsx, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.tsx, packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.tsx, packages/view/src/components/Statistics/Statistics.hook.tsx, packages/view/src/components/Statistics/Statistics.tsx, packages/view/src/components/TemporalFilter/ClocLineChart/ClocLineChart.tsx, packages/view/src/components/TemporalFilter/ClocLineChart/ClocLineChart.type.ts, packages/view/src/components/TemporalFilter/CommitLineChart/CommitLineChart.tsx, packages/view/src/components/TemporalFilter/TemporalFilter.tsx, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.hook.tsx, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.tsx, packages/view/src/components/VerticalClusterList/VerticalClusterList.tsx, packages/view/src/hooks/useGlobalData.tsx, packages/view/src/index.tsx
- [taejs PR](https://github.com/githru/githru-vscode-ext/pull/106)
taejs님의 commit log를 가져와서 작업하고싶었으나 
저의 역량 부족으로 인해 git history 차이가 어느정도 있다고 판단하였고,
rebase로 끌고와 수정하는 것과 taejs님의 코드파일 hooks/useGlobalData.tsx 파일을 그대로 복붙하는 방법 중에
후자의 방법이 비교적 수월할 것이라 판단하여 작업하였습니다.
- e88772626a4ba0d5674d46a2a5637d1a72a8043d : taejs님의 코드를 그대로 인용하였습니다.
- fe68c20a99ba50b0e9a0ce7833e45d2e02178825 : props를 모두 지워주었고, context api를 사용한 전역 데이터를 사용하였습니다.
- c8c19f51c9703aaf66995e179ea64df879060909 : partial을 사용한 전역 변수의 값이기에 undefined를 모두 처리해주어야 했는데, initial 함수에서 undefined checking을 진행하였습니다.
- d8a4e00d10a96960ca5000a76816a253173c5268 : Statistics Component에서 사용하는 데이터 타입에 맞게 data를 반환해주는 Component Hook을 만들었습니다.
- d7c38267361e9ed271a862922b8fa6d223a85e97 : ClusterGraph 컴포넌트 파일에 너무 많은 draw logic이 존재하여 전체를 Component Hook으로 …
=> feat(view): global state management using context API used by taejs

packages/view/src/App.tsx, packages/view/src/components/Detail/Detail.scss, packages/view/src/components/Detail/Detail.tsx, packages/view/src/components/Detail/Detail.util.ts, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.scss, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.tsx, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.util.ts, packages/view/src/components/Statistics/Statistics.hook.tsx, packages/view/src/components/TemporalFilter/ClocLineChart/ClocLineChart.scss, packages/view/src/components/TemporalFilter/ClocLineChart/ClocLineChart.tsx, packages/view/src/components/TemporalFilter/CommitLineChart/CommitLineChart.scss, packages/view/src/components/TemporalFilter/CommitLineChart/CommitLineChart.tsx, packages/view/src/components/TemporalFilter/TemporalFilter.tsx, packages/view/src/components/TemporalFilter/ThemeSelector/ThemeSelector.tsx, packages/view/src/components/TemporalFilter/ThemeSelector/index.ts, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.scss, packages/view/src/components/VerticalClusterList/Summary/Summary.tsx, packages/view/src/hooks/index.ts, packages/view/src/hooks/useGetTotalData.tsx, packages/view/src/hooks/useGlobalData.tsx, packages/view/src/index.tsx
- close #203 
-  author 클릭 시 해당 author 정보 보여주는 기능 구현 0cb7d01e8dd2c4ba3c9210e8a275e23cf657655f
- 스타일 통일
- line chart background color, color 통일 16cc177f539d8f8cd854956e11c170cedf9259a6
- author bar chart와 summary 툴팁 스타일 통일 725e92a002883d0cc194222e89f01cb09666339a
- summary 내 font-size 통일 725e92a002883d0cc194222e89f01cb09666339a
- 리팩토링 및 코드 정리
- TemporalFilter 내부로 lineChart 컴포넌트 이동 및 불필요한 파일 제거 f56a3d93dac92f0383095e4ea3583ab0845abdc3
- hooks 폴더 내로 hook 옮기기 78346f0003c72eacb780f8450f6b44ed849c3149
- line chart y축 제거 66d94a69f29c1c276fd66a77d2fe5065f9c75815
- detail 내 summary 리팩토링 및 단수 네이밍 적용 44825d90ed1b0674ac981f7f62db01a4f5372aeb
- ex) `0 authors -> 0 author / 1 commits -> 1 commit`
https://user-images.githubusercontent.com/69497936/193555262-add33e47-36e8-49f6-871e-8e67cb90525d.mov
- UX …
=> feat(view): add feature shows cluster by author in author bar chart

packages/analysis-engine/src/csm.ts, packages/analysis-engine/src/index.ts, packages/analysis-engine/src/types/Github.ts
CSM 생성시 PR 정보를 반영하는 기능을 추가했습니다.
Squash And Merge 를 통해 만들어진 머지커밋에 대한 CSMNode 의 source 를
Github API 를 통해 내려받은 PR정보를 기반으로 채워넣게 됩니다. (=squash 된 커밋정보 추가 표시)
- ASIS:
- TOBE:
=> feat(engine): add pr based csm

packages/vscode/src/utils/git.util.ts
#245 에서의 ssh 프로토콜 기반 remote repo 를 지원할수있도록 url 파싱 로직을 보강했습니다.
※ 현재 지원하는 remote 는 github.com 으로 제한했습니다. (추후 변경 가능)
=> fix(engine): enhance git remote url parsing regex

packages/view/src/components/TemporalFilter/ClocLineChart/ClocLineChart.scss, packages/view/src/components/TemporalFilter/ClocLineChart/ClocLineChart.tsx, packages/view/src/components/TemporalFilter/CommitLineChart/CommitLineChart.const.ts, packages/view/src/components/TemporalFilter/CommitLineChart/CommitLineChart.scss, packages/view/src/components/TemporalFilter/CommitLineChart/CommitLineChart.tsx, packages/view/src/components/TemporalFilter/TemporalFilter.hook.tsx, packages/view/src/components/TemporalFilter/TemporalFilter.scss
- close https://github.com/githru/githru-vscode-ext/issues/259
- close #166
aa1d0240fa6d4535b7c9e85ae594489e2b7c4c3b
- Bar Chart 로 구현되어 있던 기존 TemporalFilter를 Area Chart 로 변경하였습니다.
- CLOC와 COMMIT 차트 간 경계가 모호한 것 같아 중간에 Boundary 역할을 수행하는 축을 추가하였습니다.
0a0245a37ec0131677f4fbc0318172c802256c10
- window resize 시 TemporalFilter의 width가 유동적으로 변경되도록 구현했습니다.
(before)
(after)
=> enhance(view): improve TemporalFilter Component

packages/analysis-engine/src/index.ts, packages/vscode/src/extension.ts, packages/vscode/src/utils/git.util.ts
- 현재 git local repository의 branch 이름 목록을 가져옵니다.
- csm의 기준이 될 baseBranchName을 찾아옵니다.
`git branch` 커맨드로 가져온 브랜치 목록에서 baseBranchName을 찾습니다.
1. 'main' 브랜치가 있는가?
2. 'master' 브랜치가 있는가?
3. 1, 2 둘 다 없었다면, 브랜치 목록의 첫 번째 브랜치 이름을 사용
원래 `git symbolic-ref refs/remotes/origin/HEAD` 커맨드로 remotes/origin/HEAD가 가리키는 브랜치 이름을 가져오려고 했는데,
remotes가 없거나 origin이 아닌 다른 이름을 사용하면 가져올 수 없기 때문에 브랜치 이름 리스트에서 가져오는 게 가장 안전할 것 같았습니다.
=> feat(engine): get branch names and base branch name

packages/view/src/components/VerticalClusterList/Summary/Author/Author.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.hook.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.type.ts, packages/view/src/components/VerticalClusterList/Summary/Summary.util.ts
- #258 
해당 이슈 #258 에서 profile Image의 error 발생시 fallback 이미지가 느리게 로딩되는 이슈가 존재하였습니다.
하지만 네트워크 요청 속도를 '제한없음' , '빠른 3g' , '느린 3g'를 사용하여 측정해보아도 fallback 이미지가 느리게 로딩되는 이슈를 발견할 수 없었습니다.
하지만, fallback 이미지라 하면, 기존 로딩 이후 에러 발생하여 요청하는 이미지인데, 오히려 성공적으로 요청하는 이미지의 요청 속도가 느린 결과를 확인하게 되었습니다.
아래 gif 영상은 빠른 3g 요청으로 네트워크 속도를 조절하여 확인한 영상입니다.
네트워크 탭과 성능 측정을 확인한 결과, ( 네트워크 환경은 빠른 3g 입니다. )
위 이미지를 통해 실패한 이미지 로딩에 대한 fallback을 불러오나, 성공한 이미지 로딩에 대해서는 redirect를 시켜 한번더 요청을 보내는 것을 확인하실 수 있습니다.
동시에 ```md5```를 사용한 fallback src의 갯수 또한 커넥션 수의 부족 발생이 큰 문제를 야기하지 않음을 알 수 있습니다.
이미지 로딩을 최적화 하기 위해서는 fallback 갯수 제한 또한 도움이 되겠지만, redirect하는 profile Image를 최적화 하는게 시급하다 느꼈습니다.
그 결과, redirect를 방지하기 위해서는 user 고유 값이 필요하나 값이 존재하지 않아 ```이미지 사이즈 최적화```를 통해 이미지 로딩 최적화를 진행하였습니다.
기존 사용자의 profile Image의 크기는 460px이나 view에 보이는 이미지의 크기는 30px로 …
=> fix(view): Author Image

packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.hook.tsx
- closed #227 
clusterNode별 Tooltip을 추가하였습니다.
div태그를 사용하지않고, title tag를 append하여 내부 text를 clusterSize를 제공하였습니다.
rect는 2개가 존재하여 상단인 g tag에 추가하였습니다.
=> feat(view): add clusterNode Tooltip closed #227

packages/vscode/src/webview-loader.ts
vscode 최근 버전에서 webview load 하는 방식이 바뀌어서 (갑자기 ㅜ.ㅜ) 동작하지 않는 문제가 있었습니다.
해당 문제 patch 버전입니다.
@jin-Pro 아마 지난번에 말씀해주신 에러 이슈가 저것 때문일 것 같습니다. 한번 재확인 부탁드립니다.
=> fix(vscode): patch for changed vscode webview load API

.github/workflows/analysis-engine.yml, packages/analysis-engine/src/commit.util.ts, packages/analysis-engine/src/csm.ts, packages/analysis-engine/src/pullRequest.ts, packages/analysis-engine/src/stem.ts, packages/analysis-engine/src/types/CommitNode.ts, packages/analysis-engine/src/types/Github.ts, packages/analysis-engine/src/types/Stem.ts, packages/analysis-engine/src/types/index.ts
- `buildCSM` 함수에 있는 PR 관련 로직을 빼내 pullRequest.ts로 옮겼습니다.
- CSM 노드를 만드는 로직을 함수로 빼냈습니다.
- commitDict, stemDict 등 자주 사용되는 Map 자료구조를 type으로 만들었습니다.
=> refactor(engine): extract functions from csm

packages/view/src/components/Detail/Detail.scss
- #211
디테일 컴포넌트에서, commit log가 길 경우 author와 시간이 잘리는 현상을 개선했습니다.
커밋 로그는 한줄로 표현하기 위해 내용이 길 경우 ...으로 표현되게 유지했습니다.
author와 시간이 잘리는 것을 방지하기 위해 commit log 밑에 보여지게 변경했습니다.
추가적으로 commit-item이 한줄에서 두줄로 변경이 되어 마진을 좀 더 주었습니다.
현재는 커밋 로그가 길면 ...으로 표현됩니다. 그래서 상세 커밋 로그를 확인할 수 있게 지원할 수 있게 추가적으로 구현이 되면 좋을 듯 생각합니다.
관련이슈는
- #212
입니다..!
=> fix(view): show author and date info always(#211)

packages/view/src/components/VerticalClusterList/Summary/Summary.scss
- #225 
850px viewport 이하에서 `vertical cluster list summary`의 `toggle-contents-button`의 호버 스타일링이 잘리는 것을 개선하였습니다.
해당 문제 자체는 값 하나만 바꾸는 것으로 해결하였습니다.
다양한 viewport에 대한 style을 hard coded value로 지정하다보니 생긴 Human Error였던 것 같습니다. ㅎㅎ
viewport에 대해서 width를 지정해주기보다 flex-box나 grid를 이용하는 건 어떨지 의견을 추가해봅니다.
flex-box나 grid로 채울 수 있는 남은 공간을 차지하게 한다면 쉽게, 실수 없이 반응형 디자인을 할 수 있을 것 같습니다!! 😁
위 사진은 600px viewport에서의 화면입니다.
600px 미만의 size에 대해 어떻게 지원하면 좋을지도 생각해보면 좋을 것 같습니다!! 😁
=> fix(view): hover not styling correctly under 850px viewport (#225)

packages/vscode/src/extension.ts, packages/vscode/src/webview-loader.ts
- #282 
**refresh 기능 추가**
- 클러스터 노드를 불러오는 작업을 함수로 추출했습니다. 
- `extension.ts > fetchCluseterNodes()` 
- `webview-loader.ts > panel.webview.onDidReceiveMessage()`에서 받은 메시지의 커멘드에 매칭되는 서비스 수행합니다.
- `refresh` 메시지를 받은 경우,`fetchCluseterNodes()`를 호출해 최신화된 클러스터 노드를 반환합니다.
- `WebviewLoader` 구현체에 각 이벤트에 따른 비즈니스 로직을 주입하는 방식으로 구현되어 있습니다. 이벤트의 타입이 늘어날수록 의존성이 커지는 구조인데, `webview-loader.ts` 파일과 `extension.ts` 파일을 병합해 flat한 구조로 관리하는 방법을 제안합니다.
- 최초 랜더링 때, 전역객체에 data를 바인딩 하는 방식으로 `view`에 data를 전달하고 있습니다. 통일된 데이터 전달 방식 위해 최초 랜더링 역시 메시지 기반으로 받은 데이터를 사용 하도록 리팩토링 하는 것을 제안합니다.
=> feat(vscode): add refresh handler

packages/view/src/components/Statistics/Statistics.scss, packages/view/src/components/VerticalClusterList/Summary/Content/Content.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.scss, packages/view/src/components/VerticalClusterList/VerticalClusterList.scss
- #225 
- #288
<table>
<tr>
<td>
viewport가 가로로 길 때 모습
</td>
<td>
</td>
</tr>
<tr>
<td>
viewport가 가로로 좁을 때 모습
</td>
<td>
</td>
</tr>
<tr>
<td>
viewport가 좁을 때 chart가 커밋 리스트를 가림
</td>
<td>
</td>
</tr>
</table>
<table>
<tr>
<td>
viewport가 가로로 길 때 모습
</td>
<td>
</td>
</tr>
<tr>
<td>
viewport가 가로로 좁을 때 모습
</td>
<td>
</td>
</tr>
<tr>
<td>
viewport가 좁을 때 chart를 숨김
</td>
<td>
</td>
</tr>
</table>
hard coded 된 width value들을 flex 기반으로 수정하였습니다.
commit-message에 대한 responsiveness도 수정/반영하였습니다.
850px 미만의 viewport width에 대해서는 chart를 숨기는 방식으로 진행하였습니다.
flex direction을 바꾸거나 slide over로 바꾸는 등 다양한 방식으로 추가로 수정 가능할 것 같습니다.
=> fix(view): better responsiveness with flexbox

packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.util.ts
- #290 
[https://github.com/chaejunlee/avss-2023](https://github.com/chaejunlee/avss-2023)를 vscode로 열어
githru를 실행했을 때 기존 코드로는 `getFileChangesTree`가 **1.7분 (약 1027000ms)** 걸립니다.
`getFileChangesTree` 내부의 reduce 성능을 개선하여 같은 작업에 대해 **31ms**로 줄였습니다.
테스트한 리포에 대해서 성능 개선은 약 3290배 입니다.
reduce 마다 acc를 destructuring한 뒤 property를 넣는 것에서 acc에 바로 direct assign 하는 것으로 바꾸어 성능 개선을 진행했습니다.
제가 봤을 때 destructuring 하는 것이나 direct assign 하는 것이나 문법적, 의미적으로 똑같다고 생각하였습니다.
그리고 view에 제공된 fake data에 대해서 출력이 똑같은 것도 확인하였습니다. (`JSON.stringify()`로 비교)
이 부분에 대해서 혹시나 모르니 한번 더 확인 부탁드립니다.
`FileScoresMap`이 존재하는 것을 확인하였습니다.
제가 확인하였을 때는 값이 1로 고정되고 딱히 사용되는 곳이 없는 것 같은데 어떤 용도로 사용하는 것인지 궁금합니다!
=> fix(view): faster tree calculation #290

packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.scss, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.tsx, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.type.ts, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.util.ts, packages/view/src/constants/constants.tsx
- #147  
- #178 
- #220 
- AuthorBarChart를 Hotizontal에서 Vertical로 변경하였습니다.
- Constants 파일을 src폴더에 생성하였습니다.
- Author name만 표기되던 Chart를 Avatar 이미지와 name이 함께 표기되게 변경하였습니다.
이름표기는 다른 방법으로도 가능할 것 같습니다.
=> feat(view): changed author bar chart to vertical and with avatar

packages/analysis-engine/src/csm.spec.ts, packages/analysis-engine/tsconfig.json, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.type.ts, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.util.ts, packages/view/src/components/VerticalClusterList/Summary/Summary.hook.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.type.ts, packages/view/src/components/VerticalClusterList/Summary/Summary.util.ts, packages/view/tsconfig.json
별도의 이슈가 존재하지 않아서 본 PR에 작성합니다.
view와 vscode 패키지의 tsconfig에 존재하는 "suppressImplicitAnyIndexErrors"규칙은 다음과 같은 에러를 발생하고 있습니다.
에러에서는 "ignoreDeprecations" 처리를 해주면 된다고 하지만 별도의 상태 추적이 필요할 것 같기도하고, [typescript 공식문서](https://www.typescriptlang.org/tsconfig#suppressImplicitAnyIndexErrors)에서도 Using suppressImplicitAnyIndexErrors is quite a drastic approach. It is recommended to use a @ts-ignore comment instead 와 같이 언급하고 있기 때문에 해당 룰은 comment 처리했습니다.
- 여러 문제(auth와 author등의 변수명 통일 부족)들이 보이긴 하는데, 우선은 타입 에러 해결에 초점을 맞추어서 작업했습니다.
1. 이슈를 먼저 작성해야 했나? 싶네요
2. 맨 마지막 commit 작업 내용이 다음과 같은데요.
테스트를 작성해본 경험이 전무한 상태에서, 해결할 방법이 마땅히 떠오르지 않아서 타입 단언썼습니다. 혹시 다른 해결 방법이 있을까요?
=> fix(view, vscode): "suppressImplicitAnyIndexErrors" ts rule error in tsconfig.json

packages/view/src/ide/FakeIDEAdapter.ts, packages/view/src/ide/VSCodeIDEAdapter.ts, packages/view/src/types/EngineCommand.ts, packages/view/src/types/EngineMessage.ts, packages/vscode/src/webview-loader.ts
extension 실행 시 `NO COMMIT EXISTS YET` 표시됨
extension 정상 실행
- EngineMessage.commandName 을 command로 rename, vscode와 같은 네이밍 사용하도록 함
- VSCodeIDEAdapter에 vscode로부터 받아온 데이터를 파싱하는 부분 추가
웹뷰에서 데이터를 받아오기 전까지 여전히 NO COMMIT EXISTS YET 텍스트가 표시됩니다.
데이터를 받아오는 동안 보여줄 로딩 뷰 추가가 필요합니다. #332
=> fix(vscode, view): fix fetchAnalyzedData command

packages/vscode/src/extension.ts, packages/vscode/src/webview-loader.ts
#331 
- view 초기화 시 초기 데이터를 보내지 않도록 변경
이미 view에서는 초기에 넘겨준 initialData를 사용하지 않고 있어서, vscode에서도 웹뷰를 열 때 initialData를 가져오지 않도록 수정했습니다.
githru 실행 시 웹뷰가 열리는 시간이 빨라졌습니다
as-is
to-be
웹뷰가 열리는 시간이 빨라진 대신 패널에 데이터가 그려지기 전까지의 시간이 길어졌습니다
데이터를 불러오는 동안 로딩 UI가 필요합니다 - #332
=> fix(vscode): do not send initialData to view

packages/view/src/components/Detail/Detail.scss
#322 
길어서 생략된 커밋 내용에 hover 시 전체 내용 보여주기
생략된 문장 hover하면 전체 문장이 나오도록 하였습니다.
hover하여 전제 내용을 뜨게 할 때, 아래에 문장을 밀리게 하면서 내용이 나타나도록 하였는데, 옆의 commit log처럼 흰 박스에 따로  뜨는 것이 더 좋은지 의논이 필요할 것 같습니다.
=> feat(view): show entire detail hovering (#322)

packages/vscode/src/extension.ts
- window 환경에서 child_process.spawn 가 경로를 못찾는 문제 발생 (ENOENT)
- workspaceFolders.uri.path 가 window 에서의 `/c:/...` 형태의 경로를 반환함
- spawn에서 사용x
- workspaceFolders.uri.fsPath 는 window 에서의 `\\` 가 포함되어 있는 경로를 반환함
- `\\` 를 `/` 로 변경해주는 처리 추가
- spawn에서 사용o
vscode.workspace 에서 아래와 같은 방식으로 현재 경로정보를 제공함
```
console.debug(vscode.workspace.workspaceFolders)
[
{
uri: v {
scheme: 'file',
authority: '',
path: '/c:/Users/test/workspace/githru-vscode-ext/packages/view',
query: '',
fragment: '',
_formatted: 'file:///c%3A/Users/test/workspace/githru-vscode-ext/packages/view',
_fsPath: 'c:\\Users\\test\\workspace\\githru-vscode-ext\\packages\\view'
},
name: 'view',
index: 0
}
]
```
`path: '/c:/Users/test/workspace/githru-vscode-ext/packages/view'`
=> spawn에서 해당 경로를 못찾는 이슈 발생 (ENOENT)
`_fsPath: …
=> fix(vscode): window 환경에서의 spawn ENOENT 이슈 수정

packages/view/src/components/TemporalFilter/TemporalFilter.scss, packages/view/src/components/TemporalFilter/TemporalFilter.tsx, packages/view/src/components/VerticalClusterList/Summary/Author/Author.scss, packages/view/src/components/VerticalClusterList/Summary/Author/Author.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.scss
resolve #323 
TemperalFilter 컴포넌트에 선택된 사용자에 대한 클러스터만 보이도록 필터링하도록 하였고 Author style로직을 Summary에서 분리했습니다.
=> feat(view): 선택된 사용자에 대한 클러스터만 보이도록 필터링

packages/view/src/components/VerticalClusterList/Summary/Summary.scss
resolve #358 
Summary를 펼칠 때 마다 Node사이가 벌어지는 이유는 Node에 위 아래로 불필요한 padding값이 있기 때문이라고 판단하였습니다.
=> feat[view]: Summary.scss (className:detail__container) padding 수정

packages/view/src/components/Detail/Detail.scss
resolve #291 
.commit-item의 display를 flex로, justify-content를 space-between으로 설정하여 .author-date가 우측에 정렬되도록 설정.
.author-date가 한줄로 출력되도록 설정
.commit-id의 폭을 고정된 값으로 설정하여 .author-date가 보기 좋게 정렬 되도록 설정
=> feat(view): commit-item 요소를 한줄로 출력

packages/view/src/App.tsx, packages/view/src/components/FilteredAuthors/FilteredAuthors.scss, packages/view/src/components/FilteredAuthors/FilteredAuthors.tsx, packages/view/src/components/FilteredAuthors/index.ts, packages/view/src/components/TemporalFilter/TemporalFilter.scss, packages/view/src/components/TemporalFilter/TemporalFilter.tsx, packages/view/src/components/index.ts
https://github.com/githru/githru-vscode-ext/issues/370
기존에는 `TemporalFilter` 컴포넌트 내부에 위치해있던 로직을 컴포넌트로 분리했습니다.
=> feat(view): 선택된 사용자 로직 컴포넌트로 분리

packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.const.ts
resolve #347
Summary : DETAIL_HEIGHT을  245로 수정
Detail : clusterGraph.hook의 135번째 줄에서 drawClusterGraph가 DETAIL_HEIGHT을 인자로 받고 있는데 이 값이 ClusterGraph.const에서 220으로 지정되어 있었습니다.
그런데 summary의 detail_container에는 height 220px에 추가로 위, 아래 padding 값이 5px, 20px로 지정되어 있어 detail 오픈 시 높이가 어긋나는 현상이 있던 것으로 확인했습니다.
=> feat(view): ClusterGraph.const.ts의 DETAIL_HEIGHT 값 수정

packages/view/src/components/BranchSelector/BranchSelector.tsx, packages/view/src/ide/FakeIDEAdapter.ts, packages/view/src/ide/IDEPort.ts, packages/view/src/ide/VSCodeIDEAdapter.ts, packages/vscode/src/extension.ts, packages/vscode/src/utils/git.util.ts, packages/vscode/src/webview-loader.ts
related: #278, #341, #277 
- 기존 get branch list 함수에서 빈 문자열까지 함께 반환하는 내용 수정
- 기존 get branch list 함수에서 remote branch까지 가져올 수 있도록 기능 확장
- Webview에서 fetchAnalyzedData command 요청을 받아 baseBranch를 engine 함수에 전달할 수 있도록 함수 수정
- view에서 선택된 base branch를 payload에 실어 fetchAnalyzedData command로 보낼 수 있도록 IDEAdaptor method 수정
- IDEAdaptor에 sendGetBranchListCommand method 추가
- main 작업(payload 추가)은 select-box 연동 후 확인 가능
- get branch list command refactor -> remote branch까지 가져올 수 있도록 업데이트. (캡쳐 내용은 개인 test git repo대상으로 진행하였습니다.)
- git remote branch 확장에 대한 의견..?
=> feat/issue#278: add payload to fetchAnalyzedData command for changing base branch and refetching

packages/vscode/src/extension.ts, packages/vscode/src/setting-repository.ts
#329 
````typescript
const currentWorkspaceUri = vscode.workspace.workspaceFolders?.[0].uri;
if (!currentWorkspaceUri) {
throw new Error("Cannot find current workspace path");
}
...
const githubToken: string | undefined = await getGithubToken();
if (!githubToken) {
throw new Error("Cannot retrieve GitHub token");
}
````
workspaceFolders를 열 수 없거나 깃허브 토큰을 가져올 수 없는 경우 showErrorMessage를 통해 오류 메시지를 전달하도록 수정했습니다. 
당장은 type assertion을 사용했는데 추후에도 이와 같이 예외가 발생해서 사용자에게 알려줄 때가 많다면 커스텀 에러 객체를 생성해 instanceof로 처리하는 것이 좋을 것 같습니다.
=> feat(vscode): Display Error Message on Startup #329

packages/vscode/src/extension.ts, packages/vscode/src/setting-repository.ts
#373 	
````typescript
export const getGithubToken = async (secrets: vscode.SecretStorage) => {
return await secrets.get(SETTING_PROPERTY_NAMES.GITHUB_TOKEN);
};
export const setGithubToken = (secrets: vscode.SecretStorage, newGithubToken: string) => {
return secrets.store(SETTING_PROPERTY_NAMES.GITHUB_TOKEN, newGithubToken);
};
````
토큰을 주고 받는 방법을 SecretStorage을 사용하는 방식으로 교체했습니다. 기존의 workspace configuration은 모든 extension이 공유하는 설정 파일이기에 보안적으로 취약하여 이 PR을 제안했습니다.
https://code.visualstudio.com/updates/v1_80#_extension-authoring
=> feat(vscode): Enhance Github Token Security

packages/vscode/src/errors/ExtensionError.ts, packages/vscode/src/extension.ts
저장된 토큰을 찾을 수 없는 경우 이와 같은 메시지 박스를 띄우도록 수정했습니다.
````typescript
class WorkspacePathUndefinedError extends Error {
constructor(message: string) {
super(message);
this.name = "WorkspacePathUndefinedError";
}
}
class GithubTokenUndefinedError extends Error {
constructor(
message: string,
public helpUrl: string
) {
super(message);
this.name = "GithubTokenUndefinedError";
}
}
````
이와 같이 Custom Error Class를 생성하고 `instanceof`로 에러 객체를 구분하여 처리했습니다.
- Custom Error Class를 src/erros/ExtensionError.ts에 정의했는데 더 나은 위치가 있을까요?
- 에러 메시지가 적절할까요? 더 나은 문구가 있다면 추천 부탁드립니다 ☺️
=> feat(vscode): Custom Error Handling

package-lock.json, packages/vscode/package.json, packages/vscode/src/commands.ts, packages/vscode/src/credentials.ts, packages/vscode/src/extension.ts
- 기존에 직접 personal access token을 입력하는 방식 대신 `login with github` 커맨드를 실행시키면 깃허브 oauth 페이지로 연결되어 인증이 되도록 수정했습니다.
- credential.ts
`loginWithGithub`이라는 별도의 커맨드가 존재하는 것보다 launch 커맨드 실행 시 token을 가져오는 과정에서 token이 없을 경우 인증 과정이 실행되도록 수정되면 좋을것 같은데 어떻게 생각하시나요?
=> feat(vscode): replace auth with octokit

packages/analysis-engine/src/commit.util.ts, packages/analysis-engine/src/parser.spec.ts, packages/analysis-engine/src/types/CommitMessageType.ts
#187 
기존에 `:` prefix로 분류하던 것을 커밋 메세지안에 특정 커밋 타입이 포함되어 있는지 아닌지로 분류하였습니다.
commit.util.ts
CommitMessageType.ts
parser.spec.ts
특정 커밋 타입이 포함되어 있는지 아닌지로 분류하기 때문에 CommitMessageType 배열 순서에 의존하고 있습니다.
예를들어 "feat(engine): build stem & CSM based on passed branch name (#198)" 이 커밋 메세지가 존재하고 
저희의 커밋 메세지 타입 배열 순서가 아래와 같다면
```javascript
const CommitMessageTypeList = [
"feat",
"chore",
"ci",
"docs",
"build",
"fix",
"pert",
"refactor",
"revert",
"style",
"test",
];
```
커밋 타입이 `feat`이여야 하는게 배열 순서에 의존하게 되어 `build`로 분류되어 나오게 됩니다.
=> refactor(engine): commit classify based type inclueded

packages/analysis-engine/src/parser.spec.ts, packages/vscode/src/utils/NodeTypes.temps.ts, packages/vscode/src/utils/csm.mapper.ts
#361
```
export type Commit = {
id: string;
parentIds: string[];
author: GitHubUser;
committer: GitHubUser;
authorDate: string;
commitDate: string;
diffStatistics: DiffStatistics;
message: string;
tags: string[];
releaseTags: string[];
};
```
commit마다 engine에서 받은 tag 정보를 토대로 view에 tags와 releaseTags의 정보를 넘겨줍니다. 
releaseTags에는 tag들 중 'v'로 시작하거나 숫자 또는 '.'으로만 이루어진 것들을 version에 관한 정보라고 판단하고 분류해주었습니다.
view에서 사용하기 위해서는 view내의 정의된 commit의 type을  vscode의 commit type과 동일하게 변경해주어야 합니다.
후에 tag관련 처리 부분을 엔진에서 하는 것도 고려해봐도 좋을 것 같습니다.
=> feat(vscode): git tag 정보 view에게 전달

packages/analysis-engine/src/parser.spec.ts
#128
- git log에서 branches/ tags의 정보가 바뀔 경우, commit raw 테스트
(#169  에서 언급된 HEAD가 포인팅할 경우, HEAD값이 branch에 포함이 되는지에 대한 테스트도 포함하고 있습니다.)
- differenceStatistic(insert 되거나 delete된 파일들의 정보 모음)에 대한 테스트
=> test(engine): git log를 commitRaw로 바꾸기(parer), code refactoring

packages/vscode/src/errors/ExtensionError.ts, packages/vscode/src/extension.ts
#339 
- launch 과정에서 깃허브 토큰을 가져오는 동작이 실패할 경우 단순히 에러 메시지를 보여주는 것이 아닌 깃허브 인증 과정을 재시도 하도록 변경했습니다.
=> feat(vscode): retry github auth if fails

packages/view/CONTRIBUTING.md
- type guide에 type,interface 자유 사용, type keyward 지양 규칙 추가
- view는 type으로 주로 되어있고 engine은 interface로 되어있어 자유롭게 사용한다는 언급이 있으면 좋을 것 같습니다!
=> docs(view): type guide add type,interface & type keyward

packages/view/src/App.tsx, packages/view/src/components/BranchSelector/BranchSelector.tsx, packages/view/src/context/GlobalDataProvider.tsx, packages/view/src/fake-assets/branch-list.json, packages/view/src/hooks/useGlobalData.ts, packages/view/src/ide/FakeIDEAdapter.ts, packages/view/src/ide/VSCodeIDEAdapter.ts, packages/view/src/types/IDESentEvents.ts, packages/vscode/src/extension.ts, packages/vscode/src/webview-loader.ts
- #276, #278
- 현 git repo의 branch list를 가져와 select box에 렌더링합니다.
- 초기 렌더링시 sendGetBranchListMessage 호출을 통해, BranchSelector options 값 렌더링
- FakeIDEAdaptor (view dev mode)에 필요한 branchList mock data 생성
- fetchBranchList에도 workspaceStore 적용
- 기타 vscode 리팩토링
- storedAnalyzedData가 덮어쓰기 되는 부분 수정
- 모든 parsing 함수는 특정 값을 return 하도록 하고, respondToMessage 메소드에서 일괄적으로 JSON.stringify를 적용하도록 수정
- base branch(처음 선택할 브랜치) 기준 -> default branch or HEAD?
- select box css...?
=> feat: implementing fetchBranchList

packages/view/src/App.tsx, packages/view/src/components/BranchSelector/BranchSelector.tsx, packages/view/src/components/RefreshButton/RefreshButton.tsx, packages/view/src/context/GlobalDataProvider.tsx, packages/view/src/hooks/useGlobalData.ts, packages/view/src/ide/FakeIDEAdapter.ts, packages/view/src/ide/IDEPort.ts, packages/view/src/ide/VSCodeIDEAdapter.ts, packages/view/src/services/index.ts, packages/view/src/types/IDEMessage.ts, packages/view/src/types/IDESentEvents.ts, packages/vscode/src/extension.ts, packages/vscode/src/utils/git.util.ts, packages/vscode/src/webview-loader.ts
- #276
- 초기 base branch는 현재 local repository의 HEAD 위치 (git branch --show-current)
- view 영역에서는 current branch를 따로 호출하지 않고 git branchList를 호출하면서 현재 head가 가리키고 있는 branch 전달 받음
- branch selector를 통해 base branch 변경
- vscode git util 함수 변경
- getCurrentBranch 함수 생성
- `git branch --show-current`결과 값 return
- getBranches 함수 변경
- 단순 branchList만 return하던 구조에서 -> 현재 HEAD가 위치한 branch도 함께 반환
- BranchSelector onChange handler 구현
- 기타 리뷰 반영
- BranchSelector에서 현재 작업하고 있는 브랜치(HEAD)에 대한 특정 표시의 필요성 논의?
- vscode 타입 정리 -> vscode도 진행하고 있는지는 모르겠지만, 오프라인 회의나 리뷰 후 정리 되면 아래 타입 추가된 타입 내용 파일로 따로 빼겠습니다 :).
```ts
type GithruFetcher<D = unknown, P extends unknown[] = []> = (...params: P) => Promise<D>;
type GithruFetcherMap = {
fetchClusterNodes: GithruFetcher<ClusterNode[], [string]>;
fetchBranches: GithruFetcher<{ …
```
=> feat(view, vscode): implement branchSelector onChange handler

.github/workflows/e2eTests.yml, packages/view/tests/home.spec.ts
#402
- view e2e test github actions CI(yml 파일)
- 기존 home.spec.ts failed 부분 제거
- e2e test를 통과하지 못할 경우 merge 제한 등과 같은 정책 고민 필요
=> feat: when pr,  e2e test github actions ci

packages/vscode/src/utils/git.util.ts
#366  에 대한 해결입니다. 
gitRemote 정규식이 토큰이 포함되어있을 때도 허용되는 정규식 패턴으로 수정되었습니다.
=> Fix: allow github token in gitRemote

package-lock.json, package.json, packages/analysis-engine/package.json, packages/view/package.json, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.hook.tsx, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.tsx, packages/vscode/README.md, packages/vscode/package.json, packages/vscode/src/extension.ts
feat(all): ready for release 0.6.1
fix(vscode): old git has no
show-current option
old version git의 경우 (windows 2.16.2.windows.1) --show-current 옵션이 존재하지 않아 에러 발생하는 이슈 해결.
=> feat(all): ready for release 0.6.1

packages/view/src/components/Detail/Detail.hook.tsx
#507
전: 
후: 
서브 그래프와 순서가 반대라, 헷갈릴 수 있을 것 같습니다.
=> fix(view): commit 중복 bug fix

packages/vscode/src/extension.ts
#321 [vscode] githru 열리기 전까지 progress 표시
- githru 버튼을 누른 후 패널이 뜨기 전까지 githru 버튼 옆에 스피너가 표시됩니다.
- 패널이 뜨게 되면 githru 버튼 옆에 체크 표시가 됩니다.
- 패널을 닫으면 버튼이 처음 상태로 돌아옵니다. 
로딩 시 스피너 외에 패널이 뜬 후 패널이 없을 때와 구분을 위해 체크 progress를 추가 하였습니다.
[visualstuido 공식문서]
https://code.visualstudio.com/api/references/icons-in-labels
https://code.visualstudio.com/api/ux-guidelines/status-bar
https://code.visualstudio.com/api/references/vscode-api#StatusBarItem
=> feat(vscode): #321 githru 열리기 전까지 progress 표시

packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.tsx
#540 [view] Total Commit 그래프에 마우스 호버 시 깜빡임 현상 발생
- 마우스 move 시 `.style {display: none}`과 `.style {display: inline-block}`이 반복되는 것을 확인할 수 있습니다.
- Total Commit 그래프(Bar Chart)에 마우스 over 시 tooltip이 렌더링 되는 위치를 수정하였습니다.(`{e.pageY - 70}px` 을 `{e.pageY - 90}px` 으로)
- 마우스 Over 상태에서 마우스 Move 때마다 렌더링 되던 tooltip을 **마우스 Over 때 tooltip이 렌더링 되고, Move 때마다 tooltip의 위치를 조정**하도록 수정하였습니다. _(이미지2 참고)_
- tooltip의 위치가 항상 마우스보다 위에 있습니다.
- 마우스를 빠르게 움직일 경우, 움직이기 전 마우스 위치에서 tooltip이 렌더링 되고, tooltip이 렌더링 된 위치에 움직인 후의 마우스 커서가 존재할 경우 깜빡임이 발생합니다.
- 위 '깜빡임'의 원인은 렌더링 된 tooltip 위에 마우스가 위치할 경우 Bar Chart에서는 `handleMouseOut`되고, 이에 따라 tooltip이 사라지게 됩니다. Tooltip이 사라짐으로써 Bar Chart에 `handleMouseOver`가 호출됩니다. 이후 마우스가 움직이며 `handleMouseMove`가 호출됩니다. 위 과정이 반복되며 '깜빡'이는 것처럼 보이게 됩니다.
Bar Chart 외 `handleMouseOver`, `handleMouseMove` 이 …
=> fix(view): #540 Total Commit 그래프에 마우스 over, move 시 깜빡임

packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.tsx, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.type.ts
잘못 올라간 커밋 취소하기 위한 pr 입니다...! 승인 해주시면 수정 후 다시 pr 하도록 하겠습니다!
Reverts githru/githru-vscode-ext#548
=> Revert "fix(view): AuthorBarChart에서 Author 10명 넘어가는 경우 나머지는 others로 처리"

packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.scss
#528 
File Summary 차트의 배경 색상이 되는 `primary color`가 변경될 때마다 글자 색상이 동적으로 변경됩니다.
- CSS의 `filter` 속성을 사용하여 배경 색상이 어두울 때는 `white` 컬러, 배경 색상이 밝을 때는 `black` 컬러로 보입니다.
- 이슈에 첨부해주신 [링크](https://miunau.com/posts/dynamic-text-contrast-in-css)를 참고했습니다. 감사합니다. 🤗
색상 값을 계산하거나 SVG 필터를 씌우는 것보다 간단한 방법이라고 생각해서 이렇게 구현했는데요,
혹시 더 좋은 방법이 있다면 편하게 제안해주세요! 🙌🙌🙌
=> feat(view): Primary color에 따라 File Summary 글자 색상 동적 변경

packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.tsx, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.type.ts, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.util.ts, packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.scss
#553
10명의 사용자가 초과되는 경우 slice로 나눠 나머지는 Others로 분류시켰습니다. 또 그 Others bar를 클릭하게 되면 topAuthors 를 제외한 나머지(Others)의 커밋 내역들 역시 summary에 보여지도록 수정하였습니다. **다만 (#540)해당 이슈는 며칠전 수정이 되었음에도 others바에는 적용이 안되었기에 불가피하게 이전 수정 부분에서 수치를 좀 더 주었습니다.**
~~아쉬운 점은 others 바를 끝까지 타고 들어갔을때 그 이전의 author들을 보여주지 못한다는 점이 조금 아쉽습니다...ㅠ 이 부분은 따로 버튼을 넣어 뒤로가기를 만들어야만 할거 같아 해당부분 이슈 올리겠습니다...!!~~ **(해당 이슈는 이미 올라와있는 것 같아 따로 올리지 않겠습니다 #529)** 그 외에도 보다 효율적인 방법이 있다면 피드백 주시면 감사하겠습니다...!😁
=> fix(view): #553  Author(other bar) 클릭시 해당 사용자들 관련 커밋내역이 나오지는 않는 문제 수정

packages/view/src/App.scss, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.scss, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.tsx, packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.scss, packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.tsx, packages/view/src/components/Statistics/Statistics.scss, packages/view/src/components/VerticalClusterList/Summary/Summary.scss
#526 
- x scroll
<br/>
<br/>
- 그래프 title
=>
- 첫 번째 첨부해드린 사진을 보시면 이전에는 Statistics 부분의 아래쪽에  x축 scroll이 존재했었기에 개인적으로 ux가 불편하다는 생각을 했었습니다. 따라서 현재는 x축 scroll이 보이지 않도록 content 자체의 width를 변경시켜두었습니다.
- 두 번째 첨부해드린 사진은 각 그래프가 무엇을 의미하는 지 알기 어려운 사용자도 있을 수 있다는 생각이 들어서 이전에는 없었던 그래프의 title명을 추가해보았습니다..!
큰 변화는 없지만,,, 첫 pr인데 처음 보는 코드를 분석하면서 재미를 느꼈던 것 같습니다...! 앞으로도 더 많은 부분을 기여해보고 싶습니다😖🙂
=> feat(view): 레이아웃 수정

CONTRIBUTING.md
#574 
- 문법 수정
- 공식명칭에 맞게 네이밍 수정
- **메시지**의 경우 아래의 국립국어원 답변 참고
[국립국어원 답변 링크](https://x.com/urimal365/status/392110289086205952)
- vscode의 경우, 혼용하는경우가 다수 있는 듯하여 배제
=> docs: 문법 및 네이밍 수정(#574)

packages/vscode/src/credentials.ts, packages/vscode/src/extension.ts
#561
Octokit 인스턴스가 이미 있으면 바로 가져오고, 없다면 새로 만들어서 가져오는 로직이 중복되고 있었습니다.
그래서 그 부분을 private method로 따로 만들었습니다.
이 메서드가 호출되면, Octokit이 존재함이 보장됩니다.
더 좋은 방법 있다면 말씀 부탁드립니다~
=> feat(vscode): Add private method 'ensureOctokitInstance' to resolve Octokit's common logic.

packages/view/src/App.scss, packages/view/src/App.tsx, packages/view/src/components/FilteredAuthors/FilteredAuthors.scss, packages/view/src/components/FilteredAuthors/FilteredAuthors.tsx, packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.tsx, packages/view/src/components/Statistics/Statistics.scss, packages/view/src/components/VerticalClusterList/VerticalClusterList.scss, packages/view/src/components/VerticalClusterList/VerticalClusterList.tsx
close #582
- 멘토님이 말씀하셨던 대로, file icicle summary에서 file summary로 text 변경했습니다.
- 이전에는 App.tsx의 top-container에 FilteredAuthors가 속해있었는데 해당 컴포넌트는 middle-container의 VerticalClusterList와 관련이 있다고 생각되어 VerticalClusterList 내부에 두는 것으로 코드를 수정했습니다. 혹시 다른 의견이 있으시다면 남겨주세요..!!
- 첨부한 사진에서 표시한 부분인 ' Authors: ' text도 추가했습니다.
- middle container의 padding 값을 각 내부의 content에서 주는 것이 아닌, middle container 전체에 주도록 스타일 수정했습니다.
- authors 부분과 관련해 https://github.com/githru/githru-vscode-ext/pull/570 해당 pr과 충돌나는 부분이 있을 것 같아 머지하신 것을 확인하고 충돌 해결해서 추가로 push해두겠습니다!
=> fix(view): 각 content title 수정

packages/view/src/App.tsx, packages/view/src/components/VerticalClusterList/Summary/Content/Content.tsx, packages/view/src/context/GlobalDataProvider.tsx, packages/view/src/hooks/useGlobalData.ts, packages/view/src/types/RemoteGitHubInfo.ts, packages/vscode/src/extension.ts, packages/vscode/src/utils/git.util.ts, packages/vscode/src/webview-loader.ts
#486 
- 하이퍼링크 github 주소가 `owner`는 `githru`, `repo`는 `githru-vscode-ext`로 하드코딩되어 있습니다.
- `githru-vscode-ext`가 아닌 레포지토리에서 issue number 링크를 열더라도 `githru-vscode-ext` 레포지토리로 이동합니다.
- number의 `href` 주소가 remote github의 issue number 주소로 올바르게 반영됩니다.
_number에 따라 issue 또는 PR이 결정되므로 `href` 주소가 `/issue/235` 이더라도 레포지토리에서 '235번'이 PR이라면 github.com에서 `/pull/235`로 자동 redirection 됩니다._
- HTTPS로 clone한 레포지토리에서 이슈 넘버를 클릭한 결과, 올바른 github의 issue로 이동합니다. 
- SSH로 clone한 레포지토리에서 이슈 넘버를 클릭한 결과, 올바른 github의 issue로 이동합니다. 
- gitconfig가 `git@github.com:HandTris/FE-HandTris.git` 인 경우 `repo`를 'F', `owner`를 'HandTris'로 parsing하여 `repo` 정보를 사용할 수 없었음
- gitconfig가 `https://github.com/seungineer/react-toy-projcet.git`인 경우 `repo`를 'r', `owner`를 'seungineer'로 parsing하여 `repo` 정보를 사용할 수 없었음
- 정규식 수정 후 아래와 같이 올바르게 parsing 됩니다. …
=> fix(view): 커밋 메시지의 PR or Issue number 하이퍼링크 버그

packages/view/src/components/FilteredAuthors/FilteredAuthors.scss, packages/view/src/components/FilteredAuthors/FilteredAuthors.tsx
#524 
사용자가 10명 이상 선택되었을때 +more로 표시 되던 로직을 삭제하고 중복 사용자를 제거하는 로직을 추가 하였습니다.
#585 충돌로 인해 다시 pr 올립니다ㅠ...
=> fix(view): Vertical Cluster List 에서 중복된 사용자는 추가시키지 않는것으로 수정 (#524)

packages/view/src/App.tsx, packages/vscode/src/webview-loader.ts
#603
- dev 모드 실행 이미지
- 확장 개발 호스트 실행 이미지
- dev 모드에서는 vscode에서 view 단으로 postMessage 하지 않기에 owner, repo 정보를 set하지 않도록 하였습니다.
- 확장 개발 호스트 모드에서는 vscode에서 view 단으로 `postMessage` 하는 부분이 누락되어 추가하였습니다.
- dev 모드 실행이 되지 않고 있기에 빠른 검토를 요청드립니다
- #588 Issue와 같이 `postMessage`를 사용하여 vscode에서 view로 정보를 전달하는 방식은 수정될 예정입니다.
=> fix(view): dev 모드 실행 정상화

packages/view/src/ide/FakeIDEAdapter.ts
#615 
- 진한 색의 원이 커졌다가 작아졌다가 다시 커지는 중간에 종료되어 어떤 애니메이션이 실행되는지 확인이 가능합니다.
- dev 모드의 경우 로딩 시간이 필요 없지만 애니메이션 확인을 위해 의도적으로 `setTimeout`이 적용되어 있습니다.
- `setTimeout`의 시간 지연을 기존 `3000ms` 에서 `1500ms` 로 수정하였습니다.
settimeout으로 loading이 발생하는 상황을 시뮬레이션 한다는 내용이 적혀 있으면 좋을 것 같아 주석을 추가하였습니다. 잘 안 건들이는 부분이라  주석이 불필요하면 제거하도록 하겠습니다. 😁
=> feat(view): dev 모드 로딩 애니메이션 시간 축소

packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.scss, packages/view/src/components/VerticalClusterList/ClusterGraph/Draws/drawSubGraph.ts
#623
- 서브 그래프 툴팁의 가독성을 개선하기 위해 배경 스타일을 부여했습니다.
- githru 내 다른 툴팁과 동일한 디자인을 적용하여 통일성을 유지했습니다.
- 다른 툴팁과 명확하게 구분 짓고자 클래스명을 변경했습니다.
UI 리뉴얼 과정에서 툴팁 디자인도 함께 변경해도 좋을 것 같습니다 😃
=> feat(view): #623 클러스터 서브 그래프 툴팁 스타일링

packages/view/src/components/BranchSelector/BranchSelector.scss, packages/view/src/components/BranchSelector/BranchSelector.tsx, packages/view/src/components/RefreshButton/RefreshButton.scss, packages/view/src/components/RefreshButton/RefreshButton.tsx, packages/view/src/components/TemporalFilter/TemporalFilter.scss, packages/view/src/components/TemporalFilter/TemporalFilter.tsx
close #644 
- 상단 line-chart brushing 후 Reset 버튼
<br/>
<br/>
- 상단 branch selector
<br/>
<br/>
- 상단 Refresh Button (컴포넌트를 mui로 변경 - 스타일에는 변화 없습니다.)
- Button color같은 경우 디자인 시스템 팀에서 새롭게 theme을 구현할 예정이라 우선 color picker의 색상으로 지정해 둔 상태입니다. 추후 color palette 수정이 이루어진 뒤 추가 수정이 필요합니다.
- branch selector 또한 배경 색이 white인 상태입니다.
---
전체 파일 내에서 button을 검색했을 때 일반적인 Button은 mui로 수정했으나, 첨부한 사진과 같은 부분은 button으로 감싸져있지만 mui의 Button으로 수정하지는 않았습니다. 이러한 부분도 mui로의 변경이 필요하다고 생각하시면 말씀해주세요!
=> [view] 일부 컴포넌트 mui로 변경

packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.scss, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.tsx, packages/view/src/components/VerticalClusterList/ClusterGraph/Draws/drawTotalLine.ts, packages/view/src/components/VerticalClusterList/Summary/Summary.scss, packages/view/src/components/VerticalClusterList/Summary/Summary.tsx, packages/view/src/components/VerticalClusterList/VerticalClusterList.scss, packages/view/src/components/VerticalClusterList/VerticalClusterList.tsx, packages/view/src/types/ClusterGraphProps.ts
Close #640
- vertical cluster list 내에 한 개의 열이 존재합니다.
- vertical cluster graph는 한 개의 cluster에 맞는 graph(1개의 <rect>를 갖는 svg)를 의미합니다.
- vertical cluster content list가 한 행씩 렌더링 될 때, vertical cluster graph를 각각의 행 내에서 렌더링합니다.
- Vertical cluter list 내 이중 Column으로 구성되던 것을 단일 Column으로 수정하였습니다.
- 80b3f0f0572807d84adb3570f048cfdda1abdc5f
- dccad2d440b02701231d6fb3abb772feb55608f1
- 전체 cluster graph를 잇는 선이 한 번에 그려지던 것을 각 cluster graph를 렌더링할 때, 그리도록 수정하였습니다.
- 3db25167fb932b2eb9237292912d82aca2676732
- vertical cluster list 내에 두 개의 열이 존재합니다.
- vertical cluster graph는 전체 content의 cluster graph를 그리는 세로로 긴 graph(n개의 <rect>를 갖는 svg)를 의미합니다.
- vertical cluster graph가 세로로 길게 왼편에 위치하고, vertical cluster content list가 오른편에 content 별로 렌더링 됩니다.
구조가 바뀜으로써 class 명도 바뀌어야 할 것 같습니다. 이는 새로운 이슈를 만들도록 하겠습니다.
PR 올린 상태의 …
=> [view] vertical cluster list 내 cluster graph, cluster summary 단일화

packages/view/src/components/TemporalFilter/TemporalFilter.scss
#649 
- 차트의 하단까지 잘 보이는 것을 확인할 수 있습니다.
- 차트 영역 바깥으로 넘어가는 그래프도 보이도록 `overflow: visible;`속성 값을 추가했습니다.
- 임시방편으로 `overflow: visible` 속성을 추가하여 보이도록 하였습니다.
- `line-charts` 내에서 차트가 잘리지 않고 표시되도록 추후 수정이 필요할 것 같습니다.
=> [view] temporal filter 차트가 잘리는 경우에도 보이도록 수정

packages/view/src/components/BranchSelector/BranchSelector.scss, packages/view/src/components/Detail/Detail.scss, packages/view/src/components/FilteredAuthors/FilteredAuthors.scss, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.scss, packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.scss, packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.tsx, packages/view/src/components/TemporalFilter/LineChart.scss, packages/view/src/components/TemporalFilter/TemporalFilter.scss, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.scss, packages/view/src/components/VerticalClusterList/Summary/Summary.scss, packages/view/src/styles/_font.scss, packages/view/src/styles/_reset.scss
#654
- 기존에 scss에서 변수로 사이즈를 다 지정해두고 사용하지 않았기 때문에, 그래프 영역을 제외한 나머지 `font-weight` `font-size`를 사용하는 부분을 모두 변수로 교체하였습니다.
- 필요없는 함수를 제거하고, 얇게, 보통, 굵게, 아주 굵게를 제외한 `font-weight` 가짓수를 줄였습니다.
- 앞으로 컬러 시스템 등을 사용하게 되면 어차피 `@import "styles/,,,"` 로 각 scss 폴더를 불러와야 하기 때문에, 번거로움을 줄이고자 전체를 합친 `app` 자체를 불러오도록 하였습니다.
- `reset.scss` 에서 브라우저 상에서 주로 사용하는 거의 모든 태그를 하나씩 불러와서 마진, 패딩 값을 조절해주고 있어서, 전체 `*` 태그로 수정하였습니다. 이미 나열된 목록이 너무 많아 차라리 특정하게 마진, 패딩 값을 다시 늘려주는 요소만 지정해주는 게 좋을 것 같다고 판단하였습니다. 
사이즈는 1920 * 1080 (기본 브라우저 사이즈) 기준으로 캡쳐하였습니다.
브라우저 상으론 조금 더 늘려도 될 것 같긴 한데, `extension`은 조금 더 크게 보일 것 같아 살짝만 조정했습니다.
그럼에도 좀 작게 보이면 캡션 사이즈는 그대로 두고, 본문과 제목만 2px 늘려도 될 것 같습니다.
=> 폰트 속성 변수로 대체

packages/analysis-engine/src/index.ts, packages/view/src/App.tsx, packages/view/src/context/GlobalDataProvider.tsx, packages/view/src/hooks/useGlobalData.ts, packages/view/src/ide/FakeIDEAdapter.ts, packages/view/src/ide/IDEPort.ts, packages/view/src/ide/VSCodeIDEAdapter.ts, packages/view/src/types/GitLogPayload.ts, packages/view/src/types/IDEMessage.ts, packages/view/src/types/IDESentEvents.ts, packages/vscode/src/utils/git.util.ts, packages/vscode/src/webview-loader.ts
#618
view와 engine 간의 git log 추가 요청을 위한 메시징 로직을 추가하였습니다.
현재 릴리즈되어 있는([v0.6.1](https://github.com/githru/githru-vscode-ext/releases/tag/v0.6.1)) 메인 로직에 영향을 최소화하기 위해 우선 `upstream:main`에서 `feature/618` 브랜치를 따로 추가하여 작업중입니다.
engine 및 view 성능 최적화 모듈의 다른 기능들과 어느정도 병합된 후 main에 머지하는 것이 좋을 것 같아서 이렇게 진행하였고, 성능 최적화를 담당하시는 다른 분들도 우선 여기에 머지해 두는 것이 좋을 것 같은데, 이와 관련하여 의견 주셔도 좋습니다!!
https://github.com/user-attachments/assets/9b87a4ca-bbef-4c9e-9dd3-92dd3d11d172
> 초안 코드 작성의 범위
> - view
>   - 스크롤 대신 단순 버튼 클릭으로 트리거
>   - GlobalDataProvider에서 지금까지 받아온 git log(커밋노드)의 개수를 useState에 저장
>   - IDE Port & Message 요청
> - engine
>   - Message payload 파싱해서 getGitLog 재호출
>   - Message 답장
https://github.com/githru/githru-vscode-ext/issues/618#issuecomment-2273493982
- TODO
- `<TemporalFilter />`(상단 CLOC, Commit 그래프)는 전체를 …
=> [engine] 성능 최적화를 위한 view와의 메시징 방안

packages/vscode/src/webview-loader.ts
Githru의 성능 개선을 위해 캐싱을 사용했습니다.
아직 논의해야 할 부분이 많지만 우선 개발을 해보는 것이 중요하다고 생각하여 한 번 조회한 브랜치의 데이터를 캐싱하여 다시 조회하는 경우 캐싱된 데이터를 보여주는 식으로 구현하였습니다.
처음 origin/HEAD 브랜치의 데이터를 조회할 때보다 이후 데이터를 조회하는 경우 속도가 더 빠른 것을 확인 할 수 있습니다.
- webview-loader 생성시 이전에 캐시된 내용 삭제
- 최초 브랜치 조회시 테이터 캐싱
Todo
- CSM 생성 방식 이해
- 특정 기간 혹은 개수에 대한 요청이 올 때 어떻게 CSM을 생성할지 고민해보기
=> [engine] 브랜치 초기 조회시  데이터 캐싱

packages/view/src/components/Detail/Detail.scss, packages/view/src/components/Detail/Detail.tsx
#534
https://github.com/user-attachments/assets/a451234b-b4f9-4291-8088-d9d511cacbb5
1. 현재 keydown시 커밋 해시 코드가 복사되고 있는데요. 모든 키보드 입력을 처리하기보다는 Enter 키를 눌렀을 때만 커밋 해시 코드가 복사되도록 하는게 더 자연스러울것같은데 어떻게 생각하시나요?👀 추가로 불필요한 handleCommitIdCopy함수 실행도 줄일수있을것같아요! :)
2. 오픈소스에 기여하는 작업이 익숙하지 않아 문제가 있다면 알려주세요! 감사합니다😌
=> [view] 커밋 링크 추가

packages/view/tests/home.spec.ts
#669 
수정 전
수정 후
- view package의 터미널에서 `npm run test:e2e` 실행 시, 
기존에 존재하는 실패하는 테스트 케이스를 분석하여 원인을 수정하고
테스트 케이스의 의도를 명확하게 수정하였습니다.
- 리뷰를 참고해주세요!
=> [test] #669 클러스터 클릭 관련 TC 테스트 코드 수정

packages/analysis-engine/.gitignore, packages/analysis-engine/src/index.ts, packages/analysis-engine/src/summary.ts
close #579 
- 기존 커밋 요약 기능을 main 브랜치가 아닌 모든 브랜치의 STEM에서 동작하도록 합니다.
- 특정 노드의 상위 10개 커밋까지만 가져와서 요약합니다.
- 브랜치를 변경하면 summary 결과가 다르게 출력됩니다. 
formik 라이브러리에서 브랜치를 변경한 후 나온 출력물입니다.
커밋을 가져오는 기준, view에서 보여주는 방법에 대해서는 별도 이슈에서 논의할 예정입니다!
=> [engine/AI] AI 요약 기능 고도화

packages/analysis-engine/src/constant.ts, packages/analysis-engine/src/index.ts, packages/analysis-engine/src/parser.spec.ts, packages/analysis-engine/src/parser.ts, packages/vscode/src/utils/git.util.ts
closes #675 
중요한 변경하게 된 이유 설명을 빼먹어벼려서,,, 😅 이슈에도 추가해두긴 했습니다만 PR에도 남깁니다!
> 기존에 git log 포맷으로 사용하던 `fuller` 포맷은 사람이 이해하기에는 편한 포맷이지만 컴퓨터가 읽기에는 (간결한 코드로 파싱하기에는) 좀 복잡한 포맷이라고 생각했습니다.
`fuller` 포맷을 파싱하는 `getCommitRaws` 함수 코드를 봤을 때 해결하고 싶었던 부분이 조금 있었는데,
> 1. 로그를 new line 단위로 끊어서 `startWith`으로 각 라인의 첫 문장을 확인하여 파싱하는 방식이
정확히 해당 코드가 어떤 내용을 파싱하고 있는지 (`fuller` 형식에 대한 이해가 부족하다면) 한눈에 이해하기 어려움
예) `if (str.startsWith("CommitDate")` 분기에서 `CommitDate` 외에도 `commit message`와 `fileChange`를 처리함
> 2. fuller 포맷의 `“commit”`, `username <user email>`, ref 목록을 감싸는 괄호 등의 형식을 제거하는 코드가 오히려 `fuller` 형식을 모를 때에는 의도를 파악하기 어려움
> 3. line 별로 읽으면서 각 line을 카테고리별로 분리하는 for loop 한번
각 카테고리의 원소들을 다시 json 타입으로 변환하는 for loop 한번, 총 2번의 for loop를 돌게 되는데, 
이렇게 중복으로 동일한 데이터를 반복하는 것이 성능에 영향을 줄 것이라 생각
이러한 부분들을 해결해보고 싶어서 git log의 출력 형식을 변경하고, …
=> [engine] getCommitRaws 함수 개선

packages/view/src/App.scss, packages/view/src/App.tsx, packages/view/src/components/Detail/Detail.scss, packages/view/src/components/Statistics/AuthorBarChart/AuthorBarChart.scss, packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.scss, packages/view/src/components/TemporalFilter/LineChart.scss, packages/view/src/components/TemporalFilter/TemporalFilter.scss, packages/view/src/components/ThemeSelector/ThemeSelector.scss, packages/view/src/components/ThemeSelector/ThemeSelector.tsx, packages/view/src/components/VerticalClusterList/ClusterGraph/ClusterGraph.scss, packages/view/src/components/VerticalClusterList/Summary/Summary.scss, packages/view/src/constants/constants.tsx, packages/view/src/styles/_customTheme.scss, packages/view/src/styles/app.scss
#686 #647 
https://github.com/user-attachments/assets/4026ce71-abee-4470-a8b1-4b393fe24b93
사용자가 테마를 선택할 수 있는 Theme Selector를 구현했습니다.
왼쪽 상단의 버튼을 클릭하면 Theme Selector가 표시되고, 이를 이용해 테마를 선택할 수 있습니다.
- 사용자가 다시 githru에 접속을 했을 때, 기존에 설정한 theme을 저장할 방법으로 vscode의 context를 이용해보려고 합니다. (현재 PR엔 적용되어있지 않습니다.)
- 컬러에 대한 피드백 부탁드립니다 ! 색상이 막상 적용되니 별로다 ... 🥲 하는 부분도 수렴 후 반영하도록 하겠습니다. 
- 코드리뷰 부탁드립니다 🥹 특히 변수명, 구현 로직에 대한 의견 주시면 감사드리겠습니다 !!
=> [view] Theme Selector 구현 및 테마에 따른 컴포넌트 컬러 변경

package-lock.json, packages/view/package.json, packages/view/src/App.tsx, packages/view/src/components/BranchSelector/BranchSelector.tsx, packages/view/src/components/RefreshButton/RefreshButton.tsx, packages/view/src/components/TemporalFilter/TemporalFilter.tsx, packages/view/src/context/GlobalDataProvider.tsx, packages/view/src/hooks/useGlobalData.ts, packages/view/src/store/index.ts, packages/view/src/store/loading.ts, packages/view/webpack.prod.config.js
#673 
전역 상태관리를 위한 zustand를 도입했습니다.  
가장 복잡도가 낮은 loading 상태부터 기존의 context 대신 zustand의 store를 사용하도록 리팩토링 했습니다.  
handleChangeAnalyzedData가 setLoading 함수에 의존하고 있어서 임시방편으로 store의 setLoading으로 교체했고,  
data store를 만들 때 리팩토링 할 예정입니다.    
store를 이용해서 기존의 context API 상태들을 점진적으로 개선해나갈 예정입니다. 
zustand 사용에 있어서 아주 작은 팁이라도 있다면 많이 알려주세요😁😁
=> Zustand 도입 및 loading 상태 리팩토링

packages/view/src/App.scss, packages/view/src/components/TemporalFilter/TemporalFilter.scss, packages/view/src/components/TemporalFilter/TemporalFilter.tsx
#699 
- reset 버튼을 그래프 위로 띄워서 그래프의 날짜 부분이 잘리는 이슈를 해결하였습니다.
- padding 값을 조절하여 reset, refresh, theme 버튼을 양 끝 단에 맞췄습니다.
=> reset 버튼 위치 수정

packages/analysis-engine/src/parser.spec.ts
- Closes #690
- #680 
- #691
- `join` 연산을 이용해서 생성하던 `testCommitLines` 의 값을 본연의 값을 사용하도록 수정했습니다.
- 다소 포괄적인 의미를 담고 있는`testCommitLines`, `mocklog` 라는 이름을 보다 담긴 데이터 파악이 용이하도록 변경했습니다. (`testCommitHashAndRefs`, `hashAndRefs` / `fileChange`)
- 테스트 코드 내에서 반복적으로 사용되는 `testAuthorAndCommitter`, `testCommitMessage`를 재사용이 가능하도록 상수화했습니다.
git log 출력의 온전한 구조를 테스트 코드 내에서 확인할 수 있어도 괜찮겠다는 생각에 출력 구조 그대로를 테스트 코드로 만드려고 했었는데, 
테스트 코드가 길어지고 가독성이 너무 떨어지게 되는 것 같아서 현재 PR의 방식대로 값들을 조합해서 구조를 만드는 쪽으로 했습니다. (위에 적은 것 처럼 재사용을 위해서도 있고요 ㅎㅎ)
변경된 구조를 잘 아는 제 입장에서는 객관적인 평가가 어려운 것 같아 어떤 쪽이 좀 더 git log 출력의 구조를 이해하기 쉬운지 의견 남겨주시면 큰 도움이 될 것 같습니다...!! 🙇‍♀️ (개인적으로는 지금의 값을 조합하는 방식이 좀 더 읽기 쉬워보입니다...ㅎㅎㅎ)
```
// 값을 조합하는 방식
`${COMMIT_SEPARATOR}${hashAndRefs}${testAuthorAndCommitter}${testCommitMessage}`
// 전체 구조 …
```
=> [engine] getCommitRaws 테스트코드 보완

packages/vscode/src/extension.ts, packages/vscode/src/webview-loader.ts
#520 
git 연동이 안된 프로젝트에서 무한로딩 증상 개선을 위해 오른쪽 하단 toast메시지를 표기해주었습니다.  
사용자에게 깃이 연동되지 않은 프로젝트를 보여줄 때 무한로딩화면을 제거하고 하단 오른쪽에 오류 메시지를 보여줄 수 있도록 변경하였습니다.
현재 패널이 잠깐 열렸다 닫히며 깜빡임이 있는데, 추후 웹뷰 판넬 자체가 열리지 않도록 개선이 필요합니다.
관련해서 코드 피드백을 주시면 적극 반영해보도록 하겠습니다!
=> [fix]#520 git 연동이 안된 프로젝트에서 무한로딩 증상 개선

packages/view/src/App.scss, packages/view/src/components/Detail/Detail.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.const.ts, packages/view/src/components/VerticalClusterList/VerticalClusterList.scss
close #697 #719
- 복잡한 레이아웃이 아니기 때문에 `grid`에서 `flex`로 수정하였으며, 오른쪽 차트에 `flex:1` 을 주어 잘리지 않도록 하였습니다.
- 이전 이슈 #720 에서 다뤘던 말 줄임 표시를 원복하였습니다.
- 해당 이슈와는 크게 관련 없지만..! 사용하지 않는 + 다른 파일과 중복된 constant 파일이 있어 제거하였습니다.
=> [view] 레이아웃이 잘리는 문제 해결

packages/analysis-engine/package.json, packages/vscode/webpack.config.js
#634 
상기 이슈에 적힌내용을 반영하여, 작업환경을 개선합니다.
analysis-engine폴더에서 작업시, 별도의 빌드 없이 확장 프로그램의 리로드만으로 변경내용을 확인 가능합니다.
다음과 같은 화면 구성으로 작업이 가능합니다.
(좌측 : analysis-engine 폴더, 우상단:vscode 디버그 터미널, 우하단: 확장 디버깅모드 창)
이 리포지토리는 다음과 같이 세가지 패키지를 가지고 있는 모노레포의 구조입니다.
```
packages
├── analysis-engine
├── view
└── vscode
```
최초 실행시 필요한 루트의 `npm run build:all` 설정으로 각 패키지의 내용을 빌드합니다.  `vscode`패키지의 빌드 과정에서 다른 패키지들의 빌드 결과물들을 통합합니다.
최종적으로, `Visual Studio Code`가 확장 프로그램을 실행(혹은 디버깅 모드에 진입)할때는 `vscode` 패키지의 빌드 결과물인 `./dist/extension.js` 하나만 보게 됩니다.
상기의 동작구조를 밑바탕으로 원래 문제( `analysis-engine 폴더의 코드 변경 내용을 바로 알 수 있게 한다`)를 해결하기 위해서 여러 방법들을 검토했으나, 최종적으로 다음과 같은 구조가 되었습니다.
- `analysis-engine`의 터미널과 `vscode` 터미널을 열어, 각각의 터미널에서 `npn run watch` 커맨드를 실행합니다.
- 이는 `analysis-engine` 폴더를 감시하여, 해당 폴더의 변경사항이 있을 시 즉시 새로 빌드하여 해당 폴더 및 …
=> chore/#634 : 디버깅모드에서 analysis-engine의 변경을 감지하도록 변경

packages/vscode/src/webview-loader.ts
- '확장개발호스트'에서 githru가 열리지 않는 버그
- 레포지토리 내에 git이 연결되어 있음에도 panel이 `dispose`됩니다.
- '확장개발호스트'에서 githru가 열리도록 주석 처리하였습니다.
- #520 에서 다룬 issue가 재발합니다.
- 레포지토리의 git 연결 여부를 확인하던 부분을 주석 처리하였습니다.
- `analyzedData` 값의 할당 유무로 git 연결 여부를 확인하였으나 **git 연결된 경우에도 `analyzedData`에는 undefined가 할당됩니다.**
- `analyzedData`에 항상 `undefined` 값이 할당되는 원인을 모르겠습니다. 🥲
=> [vscode] git 연결된 레포지토리가 확장 개발 호스트에서 실행되지 않는 버그 임시 수정

packages/vscode/src/extension.ts, packages/vscode/src/utils/git.util.ts, packages/vscode/webpack.config.js
- related with #713 
#713 에서 말씀하신 요구사항을 적용하였습니다.
- `getLogCount`의 코드의 가독성과 유지 보수성 향상
- `pakages/vscode/webpack.config.js` 주석 제거
- `packages/vscode/src/extension.ts` 주석 제거
=> [engine] #713 요구사항 적용

packages/analysis-engine/src/index.ts, packages/analysis-engine/src/summary.ts
close #717 
vitest 레포지토리로 테스트
```
latestCommitSummary:  
- chore(deps): update dependencies
- feat(browser): support `--inspect-brk`
- fix(browser): exclude missed packages from optimization
- fix(ui): remove "filters" flickering
- fix: ignore importer when resolving Vitest
```
- git 로그인 유저로 커밋이 없는 경우
```
currentUserCommitSummary:  Please provide the commit messages you would like me to summarize. I need the actual commit messages to follow the instructions and generate the output in the desired format.
```
개인 레포지토리 테스트
```
latestCommitSummary:  
- fix: protocol 기본을 https로 변경
- fix: build error
- fix: 잘못된 파일 삭제
- 4주차 템플릿 업로드
- 5주차 템플릿 업로드
- fix: 6주차 템플릿 업로드
- 7주차 템플릿 업로드
- 8주차 템플릿 업로드
- 8주차 서평 & 소감 
```
```
currentUserCommitSummary:  
- feat: nav 설정 추가
- fix: protocol 기본을 https로 변경
- fix: …
```
=> [engine/AI] 현재 author가 작성한 커밋이 있다면 최신 10개 커밋 요약하기

packages/vscode/src/extension.ts, packages/vscode/src/utils/git.util.ts
- #712
- #713 
이전에 Worker를 사용하여 병렬적으로 로그를 받아오는 기능을 구현했습니다.
이 과정에서 항상 `컴퓨터 코어 수 - 1`개의 쓰레드를 생성하여 로그를 받아왔는데 멘토님께서 이는 메모리를 과하게 사용하는 매우 비효율적인 작업이라고 지적해주셨습니다.
따라서 로그 수에 따른 적절한 쓰레드 개수를 찾기 위해 사용하는 소요되는 메모리 양과 걸리는 시간을 평가하였습니다.
```js
setInterval(() => {
const memoryUsage = process.memoryUsage();
const rssUsage = memoryUsage.rss / 1024 / 1024; // RSS 메모리(MB)로 변환
maxMemoryUsage = Math.max(maxMemoryUsage, rssUsage);
}, 10);
```
소요되는 메모리의 양을 정확히 구할 수는 없기 때문에 위와 같이 `setInterval` 함수를 사용하여 코드가 실행되는 동안 메모리 사용량을 `10ms`마다 기록하여 최댓값을 구하였습니다.
```js
const startMemoryUsage = process.memoryUsage().rss / 1024 / 1024; // 단위 MB
// setInterval 실행
// 로그 받아오는 코드 실행
const memoryIncrease = maxMemoryUsedDuringTask - startMemoryUsage; // maxMemoryUsedDuringTask에는 setInterval에서 구한 메모리 최댓값 저장
```
시작하기 전에 현재 프로세스가 사용하는 메모리의 …
=> [engine] 로그 개수에 맞는 쓰레드 생성

packages/analysis-engine/src/parser.spec.ts, packages/analysis-engine/src/parser.ts, packages/vscode/src/utils/git.util.ts
- closes #691
- related with #675
- 테스트 input으로 쓰이는 데이터 이름의 prefix를 `test`에서 `mock`으로 변경했습니다. (https://github.com/githru/githru-vscode-ext/pull/708#pullrequestreview-2283403106 반영)
- `getCommitRaws`를 수정하다 누락되었던 commit message body를 파싱하는 로직을 추가했습니다.
- test case 추가 1 : Commit이 여러 개인 경우
fuller format 예시
```
commit a b HEAD
Author:     John Park <mail@gmail.com>
AuthorDate: Sun Sep 4 20:17:59 2022 +0900
Commit:     John Park 2 <mail2@gmail.com>
CommitDate: Sun Sep 5 20:17:59 2022 +0900
commit message
10  0       a.ts
1   0       README.md
commit a b HEAD
Author:     John Park <mail@gmail.com>
AuthorDate: Sun Sep 4 20:17:59 2022 +0900
Commit:     John Park 2 <mail2@gmail.com>
CommitDate: Sun Sep 5 20:17:59 2022 +0900
commit message
```
실제 format
```
4itc2s8hH-oA64s08h19a …
```
=> [engine] getCommitRaws 테스트케이스 추가

packages/view/src/components/@common/Author/Author.tsx
#571 
- 개선 이전 
https://github.com/user-attachments/assets/26ecd036-37ae-4ef9-aee4-539e832fab8b
- 개선 이후
https://github.com/user-attachments/assets/db7c7312-ee21-49a2-9d4b-ef73d2c1a0a9
- #685 을 개선한 기능입니다.
- git log 에 가져온 user정보와 github 계정정보가 매칭이 안되는 경우 404 페이지로 이동하게 되어서 아이콘 클릭을 비활성화 처리하였습니다.
- 추후 다른 도메인까지 확장 적용된다면 수정이 필요합니다.
=> [view] 유저 정보 매칭 실패시 유저 아이콘 클릭 비활성화

packages/vscode/src/extension.ts, packages/vscode/src/utils/git.util.ts, packages/vscode/src/webview-loader.ts
- #672 
- #743 
- 기존 브랜치를 변경 할 때마다 git 로그를 불러오는 방식에서 최초 실행 시 한 번만 불러오는 방식으로 바꿨습니다.
- 1000개 이상의 로그 수를 받아오는 경우 생성되는 쓰레드의 수를 최대 3개로 제한하였습니다.
- webview-loader에 있는 불필요한 코드를 정리하였습니다.
- `fetchClusterNodes`에 있던 `fetchGitLogInParallel` 함수 밖으로 이전
-  불필요한 `baseBranchName` 함수 제거
- 로그가 1000개 이상 일때, 코어 수가 4개 미만이라면 2개의 쓰레드, 이상이라면 3개의 쓰레드가 생성되도록 변경
혹시 위 작업을 마지막으로 해당 브랜치를 메인 브랜치와 병합해도 괜찮을까요?
=> [engine] 최대 쓰레드 수 3개 제한 및 git 로그 최초 한 번만 불러오기

packages/view/public/index.html, packages/view/src/components/ThemeSelector/ThemeSelector.tsx, packages/view/src/ide/FakeIDEAdapter.ts, packages/view/src/ide/IDEPort.ts, packages/view/src/ide/VSCodeIDEAdapter.ts, packages/view/src/services/index.ts, packages/view/src/types/IDEMessage.ts, packages/view/src/types/custom.d.ts, packages/vscode/package.json, packages/vscode/src/setting-repository.ts, packages/vscode/src/webview-loader.ts
#752 
https://github.com/user-attachments/assets/02f269d7-debb-4be9-8a18-c23ef81604eb
ThemeSelector를 이용해 선택한 테마를 재접속 시 유지할 수 있도록 구현했습니다.
로직은 다음과 같습니다: 
1. ThemeSelector 컴포넌트를 통해 테마를 선택하여 변경합니다.
2. vscode api를 통해, vscode에 메시지를 보냅니다. (`view/services`)
``` ts
public setCustomTheme(theme: string) {
const message: IDEMessage = {
command: "updateCustomTheme",
payload: JSON.stringify({ theme }),
};
this.sendMessageToIDE(message);
}
```
3. vscode가 메시지를 수신, command에 맞는 동작을 수행합니다. 
여기서는 `setTheme()` 함수를 호출하여, vscode의 configuration 중 githru.theme 값을 업데이트 합니다.
```ts
// vscode/webview-loader.ts
if (command === "updateCustomTheme") {
const colorCode = payload && JSON.parse(payload);
if (colorCode.theme) {
setTheme(colorCode.theme);
}
}
// vscode/setting-repository.ts
export const setTheme = async …
```
=> [view] Theme Selector 테마 전역 저장 및 코드 리팩토링

package-lock.json, package.json, packages/analysis-engine/package.json, packages/view/package.json, packages/vscode/README.md, packages/vscode/package.json
=> env(all): ready for v0.7.2

packages/analysis-engine/src/constant.ts, packages/analysis-engine/src/index.ts, packages/analysis-engine/src/parser.spec.ts, packages/analysis-engine/src/parser.ts, packages/vscode/src/utils/git.util.ts
- closes #759
`COMMIT_SEPARATOR`와 `GIT_LOG_SEPARATOR`를 난수 문자열로 사용
git log format
```
<COMMIT_SEPARATOR><commit hash><GIT_LOG_SEPARATOR><parent hashes><GIT_LOG_SEPARATOR><refs(branches, tags><GIT_LOG_SEPARATOR><author name><GIT_LOG_SEPARATOR><author email><GIT_LOG_SEPARATOR><author date><GIT_LOG_SEPARATOR><committer name><GIT_LOG_SEPARATOR><committer email><GIT_LOG_SEPARATOR><committer date><GIT_LOG_SEPARATOR><commit message><GIT_LOG_SEPARATOR>
<diffstat>
```
format example
```
4itc2s8hH-oA64s08h19ofyms0k2vdw7l3yjed2xwranqa0bx0oyeji6ult2I9M-0XOzvHlYPegVPpzbuiugrjiony42hzos0x8rz6aopsx3euzp6sxxthncI9M-0XOzvHlYPegVPpzbHEAD -> mainI9M-0XOzvHlYPegVPpzbJohn ParkI9M-0XOzvHlYPegVPpzbmail@gmail.comI9M-0XOzvHlYPegVPpzbSun Sep 4 20:17:59 2022 +0900I9M-0XOzvHlYPegVPpzbJohn Park …
```
=> [engine] git log 파싱에 사용되는 separator 개선

packages/view/src/components/VerticalClusterList/Summary/Summary.util.test.ts, packages/view/src/components/VerticalClusterList/Summary/Summary.util.ts
#723 
* 리팩토링 전, 테스트를 진행했습니다.
getInitData 의 주요 역할이 
1. 한 클러스터 내의 author들을 중복없이 보여준다. 
2. 클러스터의 첫번째 커밋 메세지를 노출한다. 
3. 가장 최신의 릴리스 태그를 노출한다 
로 보았는데,  1번에 대한 테스트코드를 추가해보았습니다.
1. map -> forEach로 변경
2. authorSet을 여러 군데에서 변경 및 혼동되는 변수 네이밍 변경
3. 최종 리턴값에 담길 cluster 변수를 마지막에 세팅 (여러번 객체의 값 변경 하는 방식 지양)
=>  [Refactor] SummaryUtil 리팩토링(#723)

packages/view/src/boot/raw.csv, packages/vscode/src/test/utils/getRepo.spec.ts, packages/vscode/src/utils/git.util.ts
Closes #798 
Azure DevOps URL 파싱 케이스 추가 및 getRepo 함수를 개선하였습니다.
기존 문제: getRepo 함수가 GitHub URL만 지원하여 Azure DevOps 저장소에서 오류 발생
해결 방안: Azure DevOps URL 패턴을 지원하도록 정규식 패턴 추가
지원 URL 형식:
https://organization@dev.azure.com/organization/project/_git/repository-name
https://dev.azure.com/organization/project/_git/repository-name
새 파일: src/test/utils/getRepo.spec.ts
테스트 범위:
GitHub URL 다양한 형식 검증 (HTTPS/SSH, .git 확장자 유무, 사용자명 포함 등)
Azure DevOps URL 형식 검증
잘못된 URL 형식에 대한 에러 처리 검증
Azure DevOps 사용자들의 요청에 따라 URL 파싱 지원을 추가했습니다. 기존 GitHub URL 파싱 기능은 그대로 유지하면서 Azure DevOps URL 패턴을 추가로 지원하도록 구현했습니다.
특히 다음 부분들을 중점적으로 검토해주시면 좋겠습니다:
1. Azure DevOps URL 정규식 패턴이 올바른지
2. 에러 메시지가 사용자에게 충분히 명확한지
3. 테스트 케이스가 모든 시나리오를 커버하는지
=> [vscode] Azure DevOps URL 파싱 지원 및 getRepo 함수 개선

packages/view/public/index.html, packages/view/src/App.tsx, packages/view/src/components/ThemeSelector/ThemeSelector.tsx, packages/view/src/store/index.ts, packages/view/src/store/theme.ts
#783 이슈를 확인하고,
해당이슈 관련하여 해결된 [#767 ](https://github.com/githru/githru-vscode-ext/pull/767) PR을 보다가 zustand를 적용이 안되어있음을 확인하여 작업하였습니다.
기존의 window.theme 방식 대신 Zustand를 도입하여 테마 상태를 보다 효율적으로 관리하도록 개선했습니다.
persist 미들웨어를 활용해 테마 설정을 localStorage에 저장함으로써, 웹뷰를 종료 후 다시 열더라도 마지막으로 선택한 테마가 유지됩니다.
- window.theme 전역 변수 제거
- Zustand를 이용한 테마 상태 전역 관리 구조 도입
- persist 미들웨어 적용으로 localStorage 자동 저장/복원
- 테마 초기화 useEffect를 App.tsx에도 반영하여 UX 개선
window.theme 방식은 유지보수에 불리했으며, 상태 추적이 어려웠습니다.
Zustand + persist 구조를 통해 상태 관리가 중앙화되었고, UX 및 코드 구조의 일관성이 향상되었습니다.
=> [view] refactor(theme): window.theme 제거 및 zustand + persist 기반 상태관리 적용

packages/view/src/components/Detail/Detail.scss, packages/view/src/components/Detail/Detail.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.scss
Closes #790 
Summary의 cluster-summary__info 클릭 시 나오는 Detail 컴포넌트의 내부 콘텐츠 스타일링 개선 작업을 진행했습니다.
| 기존 | 개선 후 |
|:----:|:-------:|
`commit_id가 commit date와 겹쳐 보이는 현상` + `commit message hover 시, 주변 내용들을 완전히 뒤덮는 상황`
`detail__commit-item 구조 개선` + 그 외 추가적인 스타일 개선 작업(`cluster-summary 박스 overflow 개선`과 `detail max-height 조정`)
- commit message hover 시, 다른 커밋 내역들을 가리지 않은 채 상세 메시지 확인 가능
- commit_id 겹침 현상 해결
일렬로 flex 처리 되어있었던 detail__commit-item 내부 요소들을 `commit-item__left(author, commit message)`와 `commit-item__right(author, date, commit_id)`로 이분화하여 구조를 개선하였습니다. 해당 작업을 기반으로, **space-between**으로 item 간 간격 정리를 해주었습니다.
추가적으로 commit message hover 시, 확대하고자 하는 메시지가 다른 내용들을 가리지 않도록 `absolute 되어 있던 관련 코드를 삭제시켰고`, 기존 align-items: center 처리 되었던 부분을 `flex-start 상태로 변경`시켜 깔끔한 ui로 개선시켜보았습니다.
기존 cluster-summary 박스 내부 …
=> [view] Summary 내 Detail 컴포넌트 내부 콘텐츠 스타일 개선 작업

packages/view/src/components/FilteredAuthors/FilteredAuthors.tsx
#816
- FilteredAuthors 컴포넌트 내 3중 map 구조를 flatMap과 Set을 활용하여 중복 제거와 배열 평탄화를 적용함
- 코드 가독성이 향상됨
- selectedClusters에서 저자 배열들을 flatMap과 flat으로 1차원 배열로 변환
- Set을 사용해 중복 저자명을 제거
- uniqueAuthorNames 배열을 기반으로 Author 컴포넌트 map 렌더링 방식 적용
- 기존 3중 map 구조 완전 제거 및 리팩토링 완료
- 저자 이름 중복 문제(동명이인 등)는 기존과 동일하게 이름을 기준으로만 처리되고 있습니다. 
- 따라서 향후 저자 식별에 고유 ID를 활용하는 방향을 검토해보면 좋을 것 같습니다!
=> fix: FilteredAuthors의 3중 map 구조 개선

packages/vscode/src/extension.ts
closes #839 
- repo 변수에서 잘못된 배열 접근 제거
=> fix(vscode): repo 변수에서 잘못된 배열 접근 제거

packages/githru-mcp/.gitignore, packages/githru-mcp/README.md, packages/githru-mcp/claude_desktop_config.json, packages/githru-mcp/package.json, packages/githru-mcp/src/server.ts, packages/githru-mcp/tsconfig.json
#853 
- Githru 레포 내 MCP 서버(`githru-mcp`) 패키지 추가 및 기본 툴(ping, bmi_calculator) 구현
- Claude Desktop과의 수동 등록 연동 확인
- 초기에는 수동 등록 방식으로 테스트, 이후 DXT 패키징 및 마켓플레이스 등록 여부 논의 필요
- githru-vscode-ext의 분석 산출물(JSON 캐시)와 MCP 서버를 어떻게 연계할지 설계 필요
=> [vibe] 로컬 mcp 서버 연동 with claude

packages/view/src/components/Detail/Detail.util.test.ts, packages/view/src/components/Detail/Detail.util.ts, packages/view/src/components/VerticalClusterList/Summary/Summary.util.test.ts
https://github.com/githru/githru-vscode-ext/issues/725
<br>
| Detail.util.test.ts | Summary.util.test.ts | 
|----|----|
|  <img width="400" alt="스크린샷 2025-08-10 오후 6 55 49" src="https://github.com/user-attachments/assets/667f252e-e47d-4185-a1ff-936a56eeeb2a" />  | <img width="400" alt="image" src="https://github.com/user-attachments/assets/7ffdf940-bb15-4278-9bf8-dfab181cf930" /> | 
<br>
- PR #724에서 추가된 tag와 releaseTag 기능에 대한 테스트 커버리지를 추가했습니다.
- `getCommitListDetail`의 `tagLength`, `releaseTagLength` 계산을 추가했습니다.
- tags와 releaseTags가 포함된 커밋 데이터에서 tagLength, releaseTagLength 계산이 정확한지
- 태그 정보가 정확히 반환되는지
- 클러스터에 태그가 없을 경우 빈 배열을 반환하는지
- 단일 커밋 클러스터의 태그를 정확히 집계하는지
- 다중 커밋 클러스터의 태그를 병합하고 중복을 제거하는지
- 모든 예상 태그가 포함되어 있는지
- 클러스터에 릴리즈 태그가 없을 경우 빈 문자열을 반환하는지
- 여러 릴리즈 태그가 있을 경우 최신 버전 태그를 반환하는지 …
=> [view] tag와 releaseTag에 대한 테스트 코드 추가

packages/view/src/components/Detail/Detail.scss, packages/view/src/components/Detail/Detail.tsx, packages/view/src/components/SelectedClusterGroup/SelectedClusterGroup.tsx, packages/view/src/components/VerticalClusterList/ClusterGraph/Draws/drawSubGraph.ts, packages/view/src/components/VerticalClusterList/Summary/Content/Content.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.scss, packages/view/src/components/VerticalClusterList/Summary/Summary.type.ts, packages/view/src/components/VerticalClusterList/Summary/Summary.util.ts
Closes #828
| Before | After | 
|---|---|
|  <img width="632" height="339" alt="image" src="https://github.com/user-attachments/assets/45cd7ce5-2ef4-4d28-9ea9-5499756a308e" />  | <img width="649" height="402" alt="image" src="https://github.com/user-attachments/assets/32493471-d963-4be4-8cec-8d298c1fab10" /> | 
- 커밋 메시지가 한 줄로 표시되어 가독성 부족
- 제목과 본문 구분이 어려움
- UI 레이아웃이 직관적이지 않음
- 커밋 메시지 제목과 본문이 명확하게 구분되어 표시
- 아바타-제목-메타정보의 직관적인 레이아웃
- 마우스 오버 시 본문 표시로 정보 접근성 향상
- 깔끔하고 읽기 쉬운 UI 구조
1. 커밋 메시지 구조 개선: 제목과 본문을 명확하게 분리하여 가독성 향상
2. UI 레이아웃 최적화: 아바타를 제목 옆에 배치하고 메타정보를 한 줄에 표시
3. Summary 컴포넌트 단순화: 제목만 표시하여 정보 과부하 방지
4. ClusterGraph 툴팁 개선: 커밋 메시지 제목과 본문을 두 줄로 구분하여 표시
5. 사용자 경험 개선: 본문은 필요할 때만 표시하여 정보 접근성 향상
6. 코드 품질 향상: 불필요한 중첩 구조 제거로 유지보수성 개선
- 정규표현식을 활용한 커밋 메시지 파싱
- React 상태 관리를 통한 동적 UI 처리
- CSS …
=> [fix]: 커밋 메시지 가독성 및 Detail 컴포넌트 UI 레이아웃 개선 #828

packages/view/src/components/TemporalFilter/TemporalFilter.tsx
<html>
<body>
<html><head></head><body><h1>TemporalFilter 라인 차트 데이터 처리 성능 최적화</h1>
<h2>요약</h2>
<p>TemporalFilter 컴포넌트의 라인 차트 데이터 처리 성능을 루프 연산과 데이터 변환 최적화를 통해 개선했습니다. 일반적인 저장소 크기에서 약 10-20% 더 빠른 렌더링 속도를 달성했습니다.</p>
<h2>변경사항</h2>
<ul>
<li>성능 향상을 위해 <code>forEach</code>를 <code>for-of</code> 루프로 교체</li>
<li>맵 연산 단순화 (삼항 연산자 → <code>||</code> 연산자)</li>
<li>체이닝 연산 대신 효율적인 <code>Array.from</code> 매핑 함수 사용</li>
<li>불필요한 중간 변수와 헬퍼 함수 제거</li>
</ul>
<h2>Related issue</h2>
<p>#835</p>
<h2>Result</h2>
<h3>📊 성능 개선 결과</h3>
데이터셋 크기 | 최적화 전 | 최적화 후 | 개선율
-- | -- | -- | --
100 커밋 | 0.53ms ± 0.15ms | 0.43ms ± 0.23ms | 18.9% 향상 ⚡
1,000 커밋 | 2.42ms ± 0.16ms | 2.25ms ± 0.01ms | 6.9% 향상 ✅
5,000 커밋 | 14.37ms ± 3.02ms | 12.47ms ± 0.84ms | 13.2% 향상 🚀
<blockquote>
<p><strong>주목할 점</strong>: 1,000 커밋 데이터셋에서 …
=> [refactor]: TemporalFilter 라인 차트 데이터 처리 성능 최적화

packages/vscode/src/extension.ts, packages/vscode/src/test/utils/gitParallel.spec.ts, packages/vscode/src/utils/gitParallel.ts, packages/vscode/src/utils/gitUtil.ts
#833 
기존에 구현되어 있었으나 사용되지 않던 병렬 처리 함수 fetchGitLogInParallel를 적용했습니다.
Git 로그를 가져오는 전체 실행 시간을 단축하고, 응답 시간의 변동성을 줄여 시스템의 안정성과 예측 가능성을 높이는 것을 목표로 합니다.
- 기존 단일 스레드 getGitLog 함수를 병렬 처리 방식의 fetchGitLogInParallel 함수로 교체했습니다.
- fetchGitLogInParallel 함수 빌드를 위해, parallel 함수 경로를 수정했습니다.
각 함수 자체의 실행 시간을 순수하게 측정한 결과, 병렬 처리로 인한 속도 향상을 확인했습니다.
- getGitLog (기존): 4.346초
- fetchGitLogInParallel (변경): 3.312초
- 결과: 실행시간이 1.024초 23.6% 단축되었습니다.
함수 변경 후, 사용자가 Githru를 실행했을 때의 전체적인 성능을 5회 반복 측정했습니다.
ms | getGitLog | fetchGitLogInParallel
-- | -- | --
1회 | 39.512 | 48.151
2회 | 50.751 | 42.818
3회 | 41.385 | 41.285
4회 | 37.43 | 41.404
5회 | 39.495 | 39.739
지표 | getGitLog | fetchGitLogInParallel | 변화율
-- | -- | -- | --
평균 응답 시간 (ms) | 41.715 | 42.679 | +2.31% (증가)
중앙값 (ms) | 39.512 | 41.404 | +4.79% (증가)
최소 응답 시간 (ms) | …
=> [feat] multithreads 함수 반영

packages/mcp/package.json, packages/mcp/src/common/i18n.ts, packages/mcp/src/common/types.ts, packages/mcp/src/index.ts, packages/mcp/src/locales/en.json, packages/mcp/src/locales/ko.json, packages/mcp/src/server.ts, packages/mcp/src/tool/contributorRecommender.ts, packages/mcp/src/tool/featureImpactAnalyzer.ts
#902 관련 멘토님 이슈 반영
다국어 처리 적용하였습니다
- I18n을 통한 다국어 처리
- `npm run build`시에 locales 폴더 카피
=> FEAT[vibe]: 다국어처리

packages/mcp/src/tool/featureImpactAnalyzer.ts
Issue #886 
PR #891, #909 코드 추가 및 리팩토링 작업
코드 리뷰에서 반영하여
경로 임팩트 스코어(접두사 누적 + 깊이 가중치)에 대해 두 가지 기준을 결합해 롱테일 후보를 선정하도록 수정하였습니다!!
그리고, 메트릭 기준도 상위5%, 하위5% 기준으로 정하여 수정해보았습니다!
고정 임계값 대신, 최근 6개월간 병합된 PR(최대 200건) 에서 수집한 표본 분포의 하위 5%(p05) / 상위 5%(p95) 를 경계로 사용해 현재 PR을 Low / Normal / High 로 분류합니다.
경로 임팩트 스코어(접두사 누적 + 깊이 가중치)에 대해 두 가지 기준을 결합해 롱테일 후보를 선정합니다.
1. 상위 분위 기준: 전체 경로 스코어의 p95 이상
2. 로버스트 z-score 기준: MAD 기반 z-score에서 |z| ≥ 3
3. robustZScores(values) 구현: 중앙값/ MAD 기반 → 극단치에 둔감(안정성↑)
→ 두 기준의 합집합을 pathLongTail 로 반환(중복 제거 후 스코어 내림차순 정렬)
pathDistribution은 경로 스코어 전체의 분포를 요약해 시각화/판단 근거를 제공합니다.
1. 분위수 요약: percentiles → p05, p25, p50, p75, p95, min, max, mean
2. 히스토그램: histogram → IQR(사분위범위) 기반 Freedman–Diaconis 변형으로 bin 너비를 결정
3. 최소 10, 최대 80 bins로 캡(노이즈/해상도 균형)
1. 표본 희소(n < 20): 분위 기반 신뢰 낮음 → min/max 폴백 …
=> feat: add pathDistribution (histogram/percentiles) and long-tail detection via MAD

packages/analysis-engine/src/csm.spec.ts, packages/analysis-engine/src/csm.ts, packages/analysis-engine/src/stem.ts, packages/analysis-engine/src/types/CommitNode.ts
최신순으로 CSM(Commit Summary Model) 빌드 시 squash merge 로직을 개선하여 over-squashing 문제를 해결합니다. 머지 부모 노드를 정확하게 추적하고, 적절한 범위까지만 squash가 이루어지도록 로직을 수정했습니다.
- 머지 부모 노드가 어느 stem으로 병합되었는지 추적하는 `mergedIntoStem` 필드 추가
- 이를 통해 향후 머지 포인트를 정확하게 식별 가능
- 기존: stem의 끝까지 모든 노드를 squash (over-squashing 발생)
- 개선: 다음 `mergedIntoStem` 노드 직전까지만 squash
- 이후 머지를 위해 남겨둬야 할 커밋을 보호
- 시간순 정렬: 오래된 커밋 → 최신 커밋 (올바른 순서)
- `commit.sequence` 기준 오름차순 정렬 적용
- 모든 테스트 데이터에 `mergedIntoStem` 플래그 명시
- master 브랜치와 sub1 브랜치 케이스 모두 업데이트
- 머지 구조를 명확하게 표현하여 테스트 신뢰성 향상
- `packages/analysis-engine/src/csm.ts` - CSM 빌드 로직 개선
- `packages/analysis-engine/src/csm.spec.ts` - 테스트 케이스 업데이트
- `packages/analysis-engine/src/stem.ts` - mergedIntoStem 플래그 설정
- `packages/analysis-engine/src/types/CommitNode.ts` - 타입 정의 추가
- `mergedIntoStem` 플래그 검증 테스트
- 머지 …
=> feat(engine): CSM Squash Merge 로직 개선

packages/analysis-engine/src/csm.const.ts, packages/analysis-engine/src/csm.ts, packages/analysis-engine/src/csm.util.ts
CSM 빌드 로직의 코드 구조를 개선하고 가독성을 향상시킵니다.
- `getMergeParentCommit`: 머지 커밋의 부모 커밋 조회
- `findSquashStartNodeIndex`: stem에서 특정 커밋 노드 인덱스 탐색
- `findSquashEndIndex`: squash 수집 종료 인덱스 계산
- `collectSquashNodes`: 노드 수집 및 stem에서 제거
- `extractNestedMergeParents`: 중첩된 머지의 부모 커밋 추출
- `MERGE_PARENT_INDEX`: 머지 커밋의 두 번째 부모 인덱스 (1)
- `FIRST_PARENT_INDEX`: 첫 번째 부모 인덱스 (0)
- 매직 넘버 제거로 코드 의도 명확화
- 복잡한 인라인 로직을 명확한 이름의 함수로 분리
- 각 함수에 명확한 JSDoc 주석 추가
- DFS 탐색 로직의 가독성 향상
- 코드 라인 수 감소 (106줄 → 138줄로 재구성되었으나 중복 제거됨)
- **Analysis Engine**: CSM 빌드 로직 리팩토링
- **파일 변경**: 3개 (csm.ts, csm.util.ts, csm.const.ts)
- **기능 변경**: 없음 (순수 리팩토링)
```typescript
// 인라인으로 복잡하게 작성된 로직
const mergeParentCommit = commitDict.get(baseCommitNode.commit.parents[1]);
const squashStartNodeIndex = squashStem.nodes.findIndex(({ commit: { id } }) => id …
```
=> refactor(engine): CSM 코드 구조 및 가독성 개선

packages/view/src/components/@common/GithubIssueLink/GithubIssueLink.scss, packages/view/src/components/@common/GithubIssueLink/GithubIssueLink.tsx, packages/view/src/components/@common/GithubIssueLink/GithubIssueLink.type.ts, packages/view/src/components/@common/GithubIssueLink/index.ts, packages/view/src/components/Detail/Detail.scss, packages/view/src/components/Detail/Detail.tsx, packages/view/src/components/VerticalClusterList/Summary/Content/Content.tsx, packages/view/src/components/VerticalClusterList/Summary/Summary.scss
#900
Detail과 Content 컴포넌트의 `processMessage` 함수 내 중복으로 존재하던 Github 이슈 링크 JSX 로직을 컴포넌트화하였습니다.
- **공통 컴포넌트 생성**: GitHub 이슈 링크 생성 로직 캡슐화
- **기존 컴포넌트 리팩토링**: `Detail.tsx`, `Content.tsx` 내 인라인 JSX를 `GithubIssueLink` 컴포넌트로 교체
- **스타일 중복 제거**: 이슈 링크 관련 CSS 스타일을 `GithubIssueLink.scss`로 통합
- **코드 스타일**: `Detail.scss` 내 불필요한 주석 제거
- `processMessage` 함수 내 공통 로직 분리 / 테스트
- 이슈 링크 () 괄호 패턴 매칭 안되는 오류 수정
디버깅 모드에서 아래와 같이 Merge PR와 연관된 커밋들이 각 커밋 메시지가 아닌 동일한 PR 제목/본문으로 표시됩니다.
1) 만약 의도된 동작이라면, 연관 커밋마다 동일한 PR 본문을 중복 노출할 필요성이 있는가에 대한 의문이 있습니다.
2) 의도된 동작이 아니라면 아래와 같이 Merge 커밋에만 PR 제목/본문을 노출하고, 연관 커밋은 해당 커밋의 제목/본문을 노출하는 것이 적절해 보입니다.
=> refactor(view): processMessage 함수 내 GIthubIssueLink 컴포넌트 분리

packages/analysis-engine/src/index.ts, packages/vscode/src/extension.ts, packages/vscode/src/webview-loader.ts
Closes #912 
- 대규모 저장소의 커밋 데이터를 효율적으로 로드하기 위한 페이지네이션 API를 백엔드에 구현했습니다.
- analysis-engine에 커서 기반 페이지네이션 로직을 활용하도록 수정하고, vscode 확장 기능이 이를 호출할 수 있도록 API를 연동했습니다.
- 기존의 Non-paginated CSM 로직도 남겨두었습니다. → `제거 or 유지` 의견 부탁드립니다!
- 이를 통해 프론트 view에서 페이징 기능을 구현할 수 있는 엔진 기반을 마련했습니다.
1. analysis-engine 패키지
- API 통합 (`index.ts`)
- analyzeGit 함수의 perPage, lastCommitId 파라미터
- 페이징, non페이징 { csmDict, nextCommitId, isLastPage } 일관된 구조 반환하도록 API 응답 통일
2. vscode 패키지
- API 호출 로직 (`extension.ts`)
- fetchClusterNodes 함수 : view로부터 페이징 파라미터를 받아 analyzeGit에 전달
- view에 전달할 최종 데이터 생성
- 메시지, 타입 정의 (`webview-loader.ts`)
- view: 페이징 요청을 파싱하여 처리하는 로직
- 페이징 요청과 기존의 캐시 사용 방식을 구분 (기존 코드 유지 중입니다)
- GithruFetcherMap의 타입을 API 응답 구조에 맞게 업데이트
- 이번 PR은 백엔드와 vscode 레이어의 API 인터페이스 변경에 중점을 두었습니다.
- 프론트 view에서 이 API를 사용하여 페이징을 구현하는 …
=> feat: csm pagination api

packages/view/src/components/FolderActivityFlow/ClusterVisualization.tsx, packages/view/src/components/FolderActivityFlow/FolderActivityFlow.scss, packages/view/src/components/FolderActivityFlow/FolderActivityFlow.tsx, packages/view/src/components/FolderActivityFlow/ReleaseVisualization.tsx
#941 
스토리 라인 차트 디자인 수정했습니다!
https://github.com/user-attachments/assets/0b65e43e-8090-4463-beb2-f2af07a4ed95
=> refactor(view) : 스토리라인 차트 디자인 변경

packages/analysis-engine/src/csm.spec.ts, packages/analysis-engine/src/csm.ts, packages/analysis-engine/src/index.ts, packages/analysis-engine/src/types/CSM.ts, packages/view/src/App.tsx, packages/view/src/components/@common/Author/Author.tsx, packages/view/src/components/BranchSelector/BranchSelector.tsx, packages/view/src/components/RefreshButton/RefreshButton.tsx, packages/view/src/components/Statistics/FileIcicleSummary/FileIcicleSummary.tsx, packages/view/src/components/TemporalFilter/TemporalFilter.util.ts, packages/view/src/constants/constants.tsx, packages/view/src/hooks/useAnalayzedData.ts, packages/view/src/ide/FakeIDEAdapter.ts, packages/view/src/ide/IDEPort.ts, packages/view/src/ide/VSCodeIDEAdapter.ts, packages/view/src/services/index.ts, packages/view/src/store/data.ts, packages/view/src/types/IDEMessage.ts, packages/view/src/types/IDESentEvents.ts, packages/view/src/types/Nodes.ts, packages/view/src/utils/author.ts, packages/view/webpack.prod.config.js, packages/vscode/src/extension.ts, packages/vscode/src/types/Node.ts, packages/vscode/src/webview-loader.ts
#912 
- 구현된 페이지네이션 API를 view, vscode 프론트에 구현했습니다.
- 페이징마다 매번 새로운 commitRaws, commitDict, stemDict를 재구축하는 로직을 → 캐싱을 사용해서 이미 구축된 stem을 기반으로 buildPaginatedCSMDict 함수를 사용하도록 했습니다.
- 브랜치 변경, 새로고침 버튼은 캐싱을 사용하지 않도록 합니다.
1. analyze-engine
- AnalyzeGitResult 반복되는 타입 추출
- commitRaws, commitDict, stemDict 초기 + 캐싱 처리
2. vscode
- ClusterNodesResult 반복되는 타입 추출
- engine 캐싱 로직
- fetchAnalyzedData, refresh 일때의 캐시 사용 처리 분기
3. view
- constant perpage, import 개선
- params payload 의 페이징 적용
- 더보기 버튼 처리 → 추후 무한 스크롤로 개선 예정
✅ 핵심 로직 변경 파일
* 페이징
[packages/analysis-engine/src/index.ts](https://github.com/githru/githru-vscode-ext/pull/937/files#diff-0adef9c60157dbf7f5612d148eff3b674d1b9ef453959fa2cbf30324269aa06f)
[packages/view/src/App.tsx](https://github.com/githru/githru-vscode-ext/pull/937/files#diff-dc3c054400c1c5 …
=> feat : csm pagination view

packages/view/src/components/@common/GithubIssueLink/GithubIssueLink.scss, packages/view/src/components/@common/GithubIssueLink/GithubIssueLink.tsx, packages/view/src/components/@common/GithubIssueLink/index.ts, packages/view/src/components/@common/GithubIssueLink/renderIssueLinkedNodes.tsx, packages/view/src/components/@common/GithubIssueLink/types.ts, packages/view/src/components/Detail/Detail.tsx, packages/view/src/components/Detail/Detail.type.ts, packages/view/src/components/VerticalClusterList/Summary/Content/Content.tsx, packages/view/src/types/CommitMessageParts.ts, packages/view/src/types/index.ts, packages/view/src/utils/commitMessage.test.ts, packages/view/src/utils/commitMessage.ts
#900
`Detail.tsx`, `Content.tsx`에 중복되어 있던 커밋 메시지 파싱/이슈 링크 렌더링 로직을 공통 유틸과 헬퍼로 분리하는 리팩토링 작업을 진행했습니다.
**splitMessageByIssueRefs** (`src/utils/commitMessage.ts`)
- 기존 `processMessage` 함수 로직을 공통 유틸로 분리
- 이슈 링크 컴포넌트 생성 로직 제외, 문자열 파싱(텍스트/이슈 참조 분리)만 추출
- 이슈 #900에 작성된 내용과 다르게 "이슈 번호 앞 텍스트 추출 / 마지막 텍스트 추가"와 같은 세부 단계를 별도 헬퍼로 쪼개지 않은 이유
-> 한 번의 스캔으로 메시지를 분리하기 위함. 세부 단계로 나누면 각 단계에서 문자열을 분리/탐색하고 재조립하는 과정에서 중복 탐색이나 불필요한 메모리 할당이 발생할 수 있음. 단일 함수에서 커서 기반으로 처리
- 괄호 패턴 지원
- 기존 코드상 주석 처리된 부분에 괄호가 포함된 이슈 참조도 지원한다고 되어있으나 실제로는 처리되지 않음
```
const processMessage = (message: string) => {
// GitHub 이슈 번호 패턴: #123 또는 (#123)
const regex = /(?:^|\s)(#\d+)(?:\s|$)/g;
....
}
```
-> `(#123)`, `[#123]`과 같은 패턴도 정확히 매칭하여 링크로 치환할 수 있도록 수정
- 커밋 메시지 원문 보존
- 문제) 기존 메시지 분리 시 공백 누락. 재조립 시 원문 보존 X
e.g. "Merge pull …
=> refactor(view): processMessage 함수 공통화 및 리팩토링
